schema {
  query: Query
}

type Query {
  playerById(id: Int!): Player
    @lookup
    @cacheControl(maxAge: 0)
    @cost(weight: "10")
  categoryStubById(id: Int!): Category @lookup @cacheControl(maxAge: 0)
  teams(categoryId: Int!, seasonStageId: Int!, pageIndex: Int!, pageSize: Int!): [Team!]!
    @cacheControl(maxAge: 0)
    @cost(weight: "10")
  teamById(id: Int!): Team @lookup @cacheControl(maxAge: 0) @cost(weight: "10")
  teamStandingsByCategory(categoryId: Int!, seasonStageId: Int!): TeamStandingModel!
    @cacheControl(maxAge: 0)
    @cost(weight: "10")
}

type Category @key(fields: "id") {
  id: Int!
  teams: [TeamDTO!]! @cacheControl(maxAge: 0) @cost(weight: "10")
}

type Player @key(fields: "id") {
  id: Int! @shareable
  name: String!
  shortName: String
  birthdate: DateTime
  countryId: Int!
  countryId2: Int
  height: String
  weight: String
  pictureUrl: String
  whoscoredPlayerId: Int
  sofascorePlayerId: Int
  squawkaPlayerId: Int
  goalPlayerId: Int
  internationalCaps: Int
  url: String
  transferMkName: String
  teamPosition: String
  percentageGainInLast6Rounds: Decimal!
  fantasyOwner: Int
  attackIndexInLast6Rounds: Int
  defenseIndexInLast6Rounds: Int
  marketValue: Int
  preferredFoot: String
  slug: String
  skillSets: String
  updatedDate: DateTime
  teams: [Team!]!
  teamPlayers: [TeamPlayer!]!
}

type RankRuleModel {
  group1: Int
  group2: Int
  group3: Int
  group4: Int
  group5: Int
  group6: Int
}

type Team @key(fields: "id") {
  name: String!
  uefaName: String!
  uefaRanking: Int!
  fame: Int!
  sofascoreId: Int
  shortName: String!
  web: String
  logo: String
  autoUrl: String
  theme: String
  background: String
  transferMarktUrl: String
  transferMarktName: String
  transferMarkUpdateDate: DateTime
  bet188: String
  whoscoredId: Int
  countryId: Int
  goalTeamCheck: DateTime
  transferMarktCheck: DateTime
  wsTeamCheck: DateTime
  sofascoreUpdate: DateTime
  seName: String!
  teamCategories: [TeamCategory!]!
  teamPlayers: [TeamPlayer!]!
  players: [Player!]!
  id: Int!
  categories: [Category!]! @cacheControl(maxAge: 0) @cost(weight: "10")
}

type TeamCategory {
  categoryId: Int!
  teamId: Int!
  teamGoals: Int!
  seasonStageId: Int!
  rank: Int
  lastRank: Int
  w: Int!
  d: Int
  l: Int
  gf: Int
  ga: Int
  gd: Int
  pts: Int
  p: Int
  forms: String
  homeWinStreak: Int!
  awayWinStreak: Int!
  homeUndefeated: Int!
  awayUndefeated: Int!
  homeCleanSheet: Int!
  awayCleanSheet: Int!
  homeFailedToScore: Int!
  awayFailedToScore: Int!
  homeLoseStreak: Int!
  awayLoseStreak: Int!
  winStreak: Int!
  loseStreak: Int!
  undefeated: Int!
  failedToScore: Int!
  homeScore: Int!
  awayScore: Int!
  team: Team!
}

type TeamDTO {
  id: Int!
  name: String!
}

type TeamPlayer {
  teamId: Int!
  playerId: Int!
  shirtNumber: Int
  position: String!
  seasonStageId: Int!
  goalShirtNumber: Int
  squawkaShirtNumber: Int
  status: Boolean!
  team: Team!
  player: Player!
  id: Int!
}

type TeamStandingModel {
  rankRule: RankRuleModel!
  teamStandings: [TeamStatDto!]!
  isTournament: Boolean!
  isComplete: Boolean!
}

type TeamStatDto {
  p: Int!
  w: Int!
  d: Int!
  l: Int!
  gf: Int!
  ga: Int!
  gd: Int!
  forms: String
  progress: String
  teamId: ID!
  team: String
  teamShortName: String
  teamSeName: String
  teamPossession: Float!
  pts: Int!
  rank: Int!
  lastRank: Int!
  shotsPerGame: Float!
  passAcc: Float!
  ratings: Float!
  aggressionR: Float!
  aggressionY: Float!
  aerialWonPS: Float!
}

"The scope of a cache hint."
enum CacheControlScope {
  "The value to cache is not tied to a single user."
  PUBLIC
  "The value to cache is specific to a single user."
  PRIVATE
}

enum ScalarSerializationType {
  STRING
  BOOLEAN
  INT
  FLOAT
  OBJECT
  LIST
}

"The `DateTime` scalar type represents a date and time with time zone offset information."
scalar DateTime
  @serializeAs(
    type: STRING
    pattern: "^\\d{4}-\\d{2}-\\d{2}[Tt]\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,9})?(?:[Zz]|[+-]\\d{2}:\\d{2})$"
  )
  @specifiedBy(url: "https://scalars.graphql.org/chillicream/date-time.html")

"The `Decimal` scalar type represents a decimal floating-point number with high precision."
scalar Decimal
  @serializeAs(type: FLOAT)
  @specifiedBy(url: "https://scalars.graphql.org/chillicream/decimal.html")

scalar FieldSelectionSet

"The `@cacheControl` directive may be provided for individual fields or entire object, interface or union types to provide caching hints to the executor."
directive @cacheControl(
  "The maximum amount of time this field's cached value is valid, in seconds."
  maxAge: Int
  "The maximum amount of time this field's cached value is valid in shared caches like CDNs, in seconds."
  sharedMaxAge: Int
  "If `true`, the field inherits the `maxAge` of its parent field."
  inheritMaxAge: Boolean
  "If `PRIVATE`, the field's value is specific to a single user. The default value is `PUBLIC`, which means the field's value is not tied to a single user."
  scope: CacheControlScope
  "The Vary HTTP response header describes the parts of the request message aside from the method and URL that influenced the content of the response it occurs in. Most often, this is used to create a cache key when content negotiation is in use."
  vary: [String]
) on OBJECT | FIELD_DEFINITION | INTERFACE | UNION

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost(
  "The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc."
  weight: String!
) on
  | SCALAR
  | OBJECT
  | FIELD_DEFINITION
  | ARGUMENT_DEFINITION
  | ENUM
  | INPUT_FIELD_DEFINITION

"""
The @key directive is used to designate an entity's unique key,
which identifies how to uniquely reference an instance of
an entity across different source schemas.
"""
directive @key("The field selection set syntax." fields: FieldSelectionSet!) repeatable on
  | OBJECT
  | INTERFACE

"""
The @lookup directive is used within a source schema to specify output fields
that can be used by the distributed GraphQL executor to resolve an entity by
a stable key.
"""
directive @lookup on FIELD_DEFINITION

directive @serializeAs(
  "The primitive type a scalar is serialized to."
  type: [ScalarSerializationType!]!
  "The ECMA-262 regex pattern that the serialized scalar value conforms to."
  pattern: String
) on SCALAR

directive @shareable repeatable on OBJECT | FIELD_DEFINITION
