//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Expressions;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace Catalog
{
	/// <summary>
	/// Database       : catalogdb
	/// Data Source    : tcp://localhost:49341
	/// Server Version : 17.10 (Debian 17.10-1.pgdg12+1)
	/// </summary>
	public partial class db : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<Category>             Categories            { get { return this.GetTable<Category>(); } }
		public ITable<CategorySsmMapping>   CategorySsmMappings   { get { return this.GetTable<CategorySsmMapping>(); } }
		public ITable<CategoryStageMapping> CategoryStageMappings { get { return this.GetTable<CategoryStageMapping>(); } }
		public ITable<EFMigrationsHistory>  EFMigrationsHistories { get { return this.GetTable<EFMigrationsHistory>(); } }
		public ITable<Season>               Seasons               { get { return this.GetTable<Season>(); } }
		public ITable<SeasonStageMapping>   SeasonStageMappings   { get { return this.GetTable<SeasonStageMapping>(); } }
		public ITable<Stage>                Stages                { get { return this.GetTable<Stage>(); } }

		#endregion

		partial void InitMappingSchema()
		{
		}

		#region .ctor

		public db()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public db(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public db(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public db(DataOptions<db> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="public", Name="Category")]
	public partial class Category
	{
		[PrimaryKey, Identity   ] public int            Id                     { get; set; } // integer
		[Column,     NotNull    ] public string         Name                   { get; set; } // character varying(50)
		[Column,     NotNull    ] public int            ParentCategoryId       { get; set; } // integer
		[Column,        Nullable] public string         GroupName              { get; set; } // text
		[Column,     NotNull    ] public int            Rounds                 { get; set; } // integer
		[Column,     NotNull    ] public int            SofaScoreId            { get; set; } // integer
		[Column,        Nullable] public string         CountryCSS             { get; set; } // text
		[Column,     NotNull    ] public int            CountryId              { get; set; } // integer
		[Column,     NotNull    ] public bool           Published              { get; set; } // boolean
		[Column,     NotNull    ] public int            DisplayOrder           { get; set; } // integer
		[Column,        Nullable] public double?        Coefficient            { get; set; } // double precision
		[Column,     NotNull    ] public int            FromMonth              { get; set; } // integer
		[Column,     NotNull    ] public int            ToMonth                { get; set; } // integer
		[Column,        Nullable] public string         MetaKeywords           { get; set; } // text
		[Column,        Nullable] public string         MetaDescription        { get; set; } // text
		[Column,     NotNull    ] public int            PictureId              { get; set; } // integer
		[Column,     NotNull    ] public int            PageSize               { get; set; } // integer
		[Column,     NotNull    ] public bool           ShowOnHomePage         { get; set; } // boolean
		[Column,     NotNull    ] public bool           IncludeInTopMenu       { get; set; } // boolean
		[Column,     NotNull    ] public bool           Deleted                { get; set; } // boolean
		[Column,     NotNull    ] public DateTimeOffset CreatedOnUtc           { get; set; } // timestamp (6) with time zone
		[Column,     NotNull    ] public DateTimeOffset UpdatedOnUtc           { get; set; } // timestamp (6) with time zone
		[Column,        Nullable] public string         Tags                   { get; set; } // text
		[Column,        Nullable] public int?           UefaC1                 { get; set; } // integer
		[Column,        Nullable] public int?           UefaC1Qualifiers       { get; set; } // integer
		[Column,        Nullable] public int?           EuropaLeagueQualifiers { get; set; } // integer
		[Column,        Nullable] public int?           EuropaLeague           { get; set; } // integer
		[Column,        Nullable] public int?           Relegation             { get; set; } // integer
		[Column,        Nullable] public int?           RelegationPlayOff      { get; set; } // integer
		[Column,        Nullable] public string         Transfermarkt          { get; set; } // text
		[Column,        Nullable] public int?           LeagueLogo             { get; set; } // integer
		[Column,        Nullable] public bool?          ShowStanding           { get; set; } // boolean
		[Column,     NotNull    ] public bool           IsTournament           { get; set; } // boolean
		[Column,     NotNull    ] public bool           IsData                 { get; set; } // boolean
		[Column,        Nullable] public object         Embedding              { get; set; } // USER-DEFINED
		[Column,     NotNull    ] public string         SeName                 { get; set; } // character varying(100)
		[Column,        Nullable] public string         Bet88Name              { get; set; } // character varying(100)
		[Column,        Nullable] public int?           SquawkaId              { get; set; } // integer
		[Column,        Nullable] public string         SquawkaName            { get; set; } // character varying(100)

		#region Associations

		/// <summary>
		/// FK_Category_SSM_Mapping_Category_CategoryId_BackReference (public.Category_SSM_Mapping)
		/// </summary>
		[Association(ThisKey=nameof(Id), OtherKey=nameof(Catalog.CategorySsmMapping.CategoryId), CanBeNull=true)]
		public IEnumerable<CategorySsmMapping> SSMMappingCategoryIds { get; set; }

		/// <summary>
		/// FK_Category_Stage_Mapping_Category_CategoryId_BackReference (public.Category_Stage_Mapping)
		/// </summary>
		[Association(ThisKey=nameof(Id), OtherKey=nameof(Catalog.CategoryStageMapping.CategoryId), CanBeNull=true)]
		public IEnumerable<CategoryStageMapping> StageMappingCategoryIds { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="Category_SSM_Mapping")]
	public partial class CategorySsmMapping
	{
		[Column(),                     PrimaryKey(2), NotNull] public int            SeasonStageId     { get; set; } // integer
		[Column(),                     PrimaryKey(3), NotNull] public int            CategoryId        { get; set; } // integer
		[Column(),                                    NotNull] public int            CompleteRound     { get; set; } // integer
		[Column(),                                    NotNull] public int            FromMonth         { get; set; } // integer
		[Column(),                                    NotNull] public int            ToMonth           { get; set; } // integer
		[Column(),                                    NotNull] public int            ToDateUseYearPart { get; set; } // integer
		[Column(),                                    NotNull] public int            FixtureCount      { get; set; } // integer
		[Column("CurrentRound_End"),                  NotNull] public DateTimeOffset CurrentRoundEnd   { get; set; } // timestamp (6) with time zone
		[Column("CurrentRound_Round"),                NotNull] public int            CurrentRoundRound { get; set; } // integer
		[Column("CurrentRound_Start"),                NotNull] public DateTimeOffset CurrentRoundStart { get; set; } // timestamp (6) with time zone
		[Column(),                                    NotNull] public int            LeagueRound       { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_Category_SSM_Mapping_Category_CategoryId (public.Category)
		/// </summary>
		[Association(ThisKey=nameof(CategoryId), OtherKey=nameof(Catalog.Category.Id), CanBeNull=false)]
		public Category Category { get; set; }

		/// <summary>
		/// FK_Category_SSM_Mapping_Season_Stage_Mapping_SeasonStageId (public.Season_Stage_Mapping)
		/// </summary>
		[Association(ThisKey=nameof(SeasonStageId), OtherKey=nameof(Catalog.SeasonStageMapping.Id), CanBeNull=false)]
		public SeasonStageMapping SeasonStage { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="Category_Stage_Mapping")]
	public partial class CategoryStageMapping
	{
		[PrimaryKey(1), NotNull] public int StageId             { get; set; } // integer
		[PrimaryKey(2), NotNull] public int CategoryId          { get; set; } // integer
		[Column,        NotNull] public int FromMonth           { get; set; } // integer
		[Column,        NotNull] public int ToMonth             { get; set; } // integer
		[Column,        NotNull] public int FromDateUseYearPart { get; set; } // integer
		[Column,        NotNull] public int ToDateUseYearPart   { get; set; } // integer
		[Column,        NotNull] public int FixtureCount        { get; set; } // integer
		[Column,        NotNull] public int Id                  { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_Category_Stage_Mapping_Category_CategoryId (public.Category)
		/// </summary>
		[Association(ThisKey=nameof(CategoryId), OtherKey=nameof(Catalog.Category.Id), CanBeNull=false)]
		public Category Category { get; set; }

		/// <summary>
		/// FK_Category_Stage_Mapping_Stage_StageId (public.Stage)
		/// </summary>
		[Association(ThisKey=nameof(StageId), OtherKey=nameof(Catalog.Stage.Id), CanBeNull=false)]
		public Stage Stage { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="__EFMigrationsHistory")]
	public partial class EFMigrationsHistory
	{
		[PrimaryKey, NotNull] public string MigrationId    { get; set; } // character varying(150)
		[Column,     NotNull] public string ProductVersion { get; set; } // character varying(32)
	}

	[Table(Schema="public", Name="Season")]
	public partial class Season
	{
		[PrimaryKey, Identity   ] public int    Id           { get; set; } // integer
		[Column,     NotNull    ] public string Year         { get; set; } // text
		[Column,        Nullable] public int?   DisplayOrder { get; set; } // integer
		[Column,     NotNull    ] public int    Year2        { get; set; } // integer
		[Column,     NotNull    ] public bool   Status       { get; set; } // boolean

		#region Associations

		/// <summary>
		/// FK_Season_Stage_Mapping_Season_SeasonId_BackReference (public.Season_Stage_Mapping)
		/// </summary>
		[Association(ThisKey=nameof(Id), OtherKey=nameof(Catalog.SeasonStageMapping.SeasonId), CanBeNull=true)]
		public IEnumerable<SeasonStageMapping> StageMappingSeasonIds { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="Season_Stage_Mapping")]
	public partial class SeasonStageMapping
	{
		[Column,     NotNull ] public int  StageId    { get; set; } // integer
		[Column,     NotNull ] public int  SeasonId   { get; set; } // integer
		[Column,     NotNull ] public bool IsComplete { get; set; } // boolean
		[Column,     NotNull ] public bool Status     { get; set; } // boolean
		[PrimaryKey, Identity] public int  Id         { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_Category_SSM_Mapping_Season_Stage_Mapping_SeasonStageId_BackReference (public.Category_SSM_Mapping)
		/// </summary>
		[Association(ThisKey=nameof(Id), OtherKey=nameof(Catalog.CategorySsmMapping.SeasonStageId), CanBeNull=true)]
		public IEnumerable<CategorySsmMapping> CategorySSMMappingSeasonStageMappingSeasonStageIds { get; set; }

		/// <summary>
		/// FK_Season_Stage_Mapping_Season_SeasonId (public.Season)
		/// </summary>
		[Association(ThisKey=nameof(SeasonId), OtherKey=nameof(Catalog.Season.Id), CanBeNull=false)]
		public Season Season { get; set; }

		/// <summary>
		/// FK_Season_Stage_Mapping_Stage_StageId (public.Stage)
		/// </summary>
		[Association(ThisKey=nameof(StageId), OtherKey=nameof(Catalog.Stage.Id), CanBeNull=false)]
		public Stage Stage { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="Stage")]
	public partial class Stage
	{
		[PrimaryKey, Identity   ] public int    Id                { get; set; } // integer
		[Column,     NotNull    ] public string Name              { get; set; } // character varying(50)
		[Column,        Nullable] public string C1WhoscoredName   { get; set; } // text
		[Column,        Nullable] public string C3WhoscoredName   { get; set; } // text
		[Column,        Nullable] public string EuroWhoscoredName { get; set; } // text
		[Column,        Nullable] public string WCWhoscoredName   { get; set; } // text
		[Column,        Nullable] public string C1SofascoreName   { get; set; } // text
		[Column,        Nullable] public string C3SofascoreName   { get; set; } // text
		[Column,        Nullable] public string EuroSofascoreName { get; set; } // text
		[Column,        Nullable] public string WCSofascoreName   { get; set; } // text
		[Column,        Nullable] public int?   ParentId          { get; set; } // integer
		[Column,        Nullable] public bool?  GroupStage        { get; set; } // boolean
		[Column,     NotNull    ] public int    DisplayOrder      { get; set; } // integer
		[Column,        Nullable] public int?   NoOfMatches       { get; set; } // integer
		[Column,     NotNull    ] public int    Round             { get; set; } // integer
		[Column,     NotNull    ] public bool   Display           { get; set; } // boolean

		#region Associations

		/// <summary>
		/// FK_Category_Stage_Mapping_Stage_StageId_BackReference (public.Category_Stage_Mapping)
		/// </summary>
		[Association(ThisKey=nameof(Id), OtherKey=nameof(Catalog.CategoryStageMapping.StageId), CanBeNull=true)]
		public IEnumerable<CategoryStageMapping> CategoryMappingStageIds { get; set; }

		/// <summary>
		/// FK_Season_Stage_Mapping_Stage_StageId_BackReference (public.Season_Stage_Mapping)
		/// </summary>
		[Association(ThisKey=nameof(Id), OtherKey=nameof(Catalog.SeasonStageMapping.StageId), CanBeNull=true)]
		public IEnumerable<SeasonStageMapping> SeasonMappingStageIds { get; set; }

		#endregion
	}

	public static partial class SqlFunctions
	{
		#region ArrayToHalfvec

		[Sql.Function(Name="public.array_to_halfvec", ServerSideOnly=true)]
		public static object ArrayToHalfvec(object par14, int? par15, bool? par16)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region ArrayToSparsevec

		[Sql.Function(Name="public.array_to_sparsevec", ServerSideOnly=true)]
		public static object ArrayToSparsevec(object par30, int? par31, bool? par32)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region ArrayToVector

		[Sql.Function(Name="public.array_to_vector", ServerSideOnly=true)]
		public static object ArrayToVector(object par46, int? par47, bool? par48)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region Avg

		[Sql.Function(Name="public.\"avg\"", ServerSideOnly=true, IsAggregate = true, ArgIndices = new[] { 0 })]
		public static object Avg<TSource>(this IEnumerable<TSource> src, Expression<Func<TSource, object>> par52)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region BinaryQuantize

		[Sql.Function(Name="public.binary_quantize", ServerSideOnly=true)]
		public static BitArray BinaryQuantize(object par56)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region CosineDistance

		[Sql.Function(Name="public.cosine_distance", ServerSideOnly=true)]
		public static double? CosineDistance(object par64, object par65)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region Halfvec

		[Sql.Function(Name="public.halfvec", ServerSideOnly=true)]
		public static object Halfvec(object par67, int? par68, bool? par69)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecAccum

		[Sql.Function(Name="public.halfvec_accum", ServerSideOnly=true)]
		public static object HalfvecAccum(object par71, object par72)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecAdd

		[Sql.Function(Name="public.halfvec_add", ServerSideOnly=true)]
		public static object HalfvecAdd(object par74, object par75)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecAvg

		[Sql.Function(Name="public.halfvec_avg", ServerSideOnly=true)]
		public static object HalfvecAvg(object par77)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecCmp

		[Sql.Function(Name="public.halfvec_cmp", ServerSideOnly=true)]
		public static int? HalfvecCmp(object par79, object par80)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecCombine

		[Sql.Function(Name="public.halfvec_combine", ServerSideOnly=true)]
		public static object HalfvecCombine(object par82, object par83)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecConcat

		[Sql.Function(Name="public.halfvec_concat", ServerSideOnly=true)]
		public static object HalfvecConcat(object par85, object par86)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecEq

		[Sql.Function(Name="public.halfvec_eq", ServerSideOnly=true)]
		public static bool? HalfvecEq(object par88, object par89)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecGe

		[Sql.Function(Name="public.halfvec_ge", ServerSideOnly=true)]
		public static bool? HalfvecGe(object par91, object par92)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecGt

		[Sql.Function(Name="public.halfvec_gt", ServerSideOnly=true)]
		public static bool? HalfvecGt(object par94, object par95)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecIn

		[Sql.Function(Name="public.halfvec_in", ServerSideOnly=true)]
		public static object HalfvecIn(object par97, int? par98, int? par99)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecL2SquaredDistance

		[Sql.Function(Name="public.halfvec_l2_squared_distance", ServerSideOnly=true)]
		public static double? HalfvecL2SquaredDistance(object par101, object par102)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecLe

		[Sql.Function(Name="public.halfvec_le", ServerSideOnly=true)]
		public static bool? HalfvecLe(object par104, object par105)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecLt

		[Sql.Function(Name="public.halfvec_lt", ServerSideOnly=true)]
		public static bool? HalfvecLt(object par107, object par108)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecMul

		[Sql.Function(Name="public.halfvec_mul", ServerSideOnly=true)]
		public static object HalfvecMul(object par110, object par111)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecNe

		[Sql.Function(Name="public.halfvec_ne", ServerSideOnly=true)]
		public static bool? HalfvecNe(object par113, object par114)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecNegativeInnerProduct

		[Sql.Function(Name="public.halfvec_negative_inner_product", ServerSideOnly=true)]
		public static double? HalfvecNegativeInnerProduct(object par116, object par117)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecOut

		[Sql.Function(Name="public.halfvec_out", ServerSideOnly=true)]
		public static object HalfvecOut(object par119)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecRecv

		[Sql.Function(Name="public.halfvec_recv", ServerSideOnly=true)]
		public static object HalfvecRecv(object par121, int? par122, int? par123)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecSend

		[Sql.Function(Name="public.halfvec_send", ServerSideOnly=true)]
		public static byte[] HalfvecSend(object par125)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecSphericalDistance

		[Sql.Function(Name="public.halfvec_spherical_distance", ServerSideOnly=true)]
		public static double? HalfvecSphericalDistance(object par127, object par128)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecSub

		[Sql.Function(Name="public.halfvec_sub", ServerSideOnly=true)]
		public static object HalfvecSub(object par130, object par131)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecToFloat4

		[Sql.Function(Name="public.halfvec_to_float4", ServerSideOnly=true)]
		public static object HalfvecToFloat4(object par133, int? par134, bool? par135)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecToSparsevec

		[Sql.Function(Name="public.halfvec_to_sparsevec", ServerSideOnly=true)]
		public static object HalfvecToSparsevec(object par137, int? par138, bool? par139)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecToVector

		[Sql.Function(Name="public.halfvec_to_vector", ServerSideOnly=true)]
		public static object HalfvecToVector(object par141, int? par142, bool? par143)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HalfvecTypmodIn

		[Sql.Function(Name="public.halfvec_typmod_in", ServerSideOnly=true)]
		public static int? HalfvecTypmodIn(object par145)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HammingDistance

		[Sql.Function(Name="public.hamming_distance", ServerSideOnly=true)]
		public static double? HammingDistance(BitArray par147, BitArray par148)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HnswBitSupport

		[Sql.Function(Name="public.hnsw_bit_support", ServerSideOnly=true)]
		public static object HnswBitSupport(object par150)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HnswHalfvecSupport

		[Sql.Function(Name="public.hnsw_halfvec_support", ServerSideOnly=true)]
		public static object HnswHalfvecSupport(object par152)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region HnswSparsevecSupport

		[Sql.Function(Name="public.hnsw_sparsevec_support", ServerSideOnly=true)]
		public static object HnswSparsevecSupport(object par154)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region Hnswhandler

		[Sql.Function(Name="public.hnswhandler", ServerSideOnly=true)]
		public static object Hnswhandler(object par156)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region InnerProduct

		[Sql.Function(Name="public.inner_product", ServerSideOnly=true)]
		public static double? InnerProduct(object par164, object par165)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region IvfflatBitSupport

		[Sql.Function(Name="public.ivfflat_bit_support", ServerSideOnly=true)]
		public static object IvfflatBitSupport(object par167)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region IvfflatHalfvecSupport

		[Sql.Function(Name="public.ivfflat_halfvec_support", ServerSideOnly=true)]
		public static object IvfflatHalfvecSupport(object par169)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region Ivfflathandler

		[Sql.Function(Name="public.ivfflathandler", ServerSideOnly=true)]
		public static object Ivfflathandler(object par171)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region JaccardDistance

		[Sql.Function(Name="public.jaccard_distance", ServerSideOnly=true)]
		public static double? JaccardDistance(BitArray par173, BitArray par174)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region L1Distance

		[Sql.Function(Name="public.l1_distance", ServerSideOnly=true)]
		public static double? L1Distance(object par182, object par183)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region L2Distance

		[Sql.Function(Name="public.l2_distance", ServerSideOnly=true)]
		public static double? L2Distance(object par191, object par192)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region L2Norm

		[Sql.Function(Name="public.l2_norm", ServerSideOnly=true)]
		public static double? L2Norm(object par196)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region L2Normalize

		[Sql.Function(Name="public.l2_normalize", ServerSideOnly=true)]
		public static object L2Normalize(object par202)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region Sparsevec

		[Sql.Function(Name="public.sparsevec", ServerSideOnly=true)]
		public static object Sparsevec(object par204, int? par205, bool? par206)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecCmp

		[Sql.Function(Name="public.sparsevec_cmp", ServerSideOnly=true)]
		public static int? SparsevecCmp(object par208, object par209)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecEq

		[Sql.Function(Name="public.sparsevec_eq", ServerSideOnly=true)]
		public static bool? SparsevecEq(object par211, object par212)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecGe

		[Sql.Function(Name="public.sparsevec_ge", ServerSideOnly=true)]
		public static bool? SparsevecGe(object par214, object par215)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecGt

		[Sql.Function(Name="public.sparsevec_gt", ServerSideOnly=true)]
		public static bool? SparsevecGt(object par217, object par218)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecIn

		[Sql.Function(Name="public.sparsevec_in", ServerSideOnly=true)]
		public static object SparsevecIn(object par220, int? par221, int? par222)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecL2SquaredDistance

		[Sql.Function(Name="public.sparsevec_l2_squared_distance", ServerSideOnly=true)]
		public static double? SparsevecL2SquaredDistance(object par224, object par225)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecLe

		[Sql.Function(Name="public.sparsevec_le", ServerSideOnly=true)]
		public static bool? SparsevecLe(object par227, object par228)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecLt

		[Sql.Function(Name="public.sparsevec_lt", ServerSideOnly=true)]
		public static bool? SparsevecLt(object par230, object par231)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecNe

		[Sql.Function(Name="public.sparsevec_ne", ServerSideOnly=true)]
		public static bool? SparsevecNe(object par233, object par234)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecNegativeInnerProduct

		[Sql.Function(Name="public.sparsevec_negative_inner_product", ServerSideOnly=true)]
		public static double? SparsevecNegativeInnerProduct(object par236, object par237)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecOut

		[Sql.Function(Name="public.sparsevec_out", ServerSideOnly=true)]
		public static object SparsevecOut(object par239)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecRecv

		[Sql.Function(Name="public.sparsevec_recv", ServerSideOnly=true)]
		public static object SparsevecRecv(object par241, int? par242, int? par243)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecSend

		[Sql.Function(Name="public.sparsevec_send", ServerSideOnly=true)]
		public static byte[] SparsevecSend(object par245)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecToHalfvec

		[Sql.Function(Name="public.sparsevec_to_halfvec", ServerSideOnly=true)]
		public static object SparsevecToHalfvec(object par247, int? par248, bool? par249)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecToVector

		[Sql.Function(Name="public.sparsevec_to_vector", ServerSideOnly=true)]
		public static object SparsevecToVector(object par251, int? par252, bool? par253)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region SparsevecTypmodIn

		[Sql.Function(Name="public.sparsevec_typmod_in", ServerSideOnly=true)]
		public static int? SparsevecTypmodIn(object par255)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region Subvector

		[Sql.Function(Name="public.subvector", ServerSideOnly=true)]
		public static object Subvector(object par261, int? par262, int? par263)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region Sum

		[Sql.Function(Name="public.\"sum\"", ServerSideOnly=true, IsAggregate = true, ArgIndices = new[] { 0 })]
		public static object Sum<TSource>(this IEnumerable<TSource> src, Expression<Func<TSource, object>> par267)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region Vector

		[Sql.Function(Name="public.vector", ServerSideOnly=true)]
		public static object Vector(object par269, int? par270, bool? par271)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorAccum

		[Sql.Function(Name="public.vector_accum", ServerSideOnly=true)]
		public static object VectorAccum(object par273, object par274)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorAdd

		[Sql.Function(Name="public.vector_add", ServerSideOnly=true)]
		public static object VectorAdd(object par276, object par277)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorAvg

		[Sql.Function(Name="public.vector_avg", ServerSideOnly=true)]
		public static object VectorAvg(object par279)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorCmp

		[Sql.Function(Name="public.vector_cmp", ServerSideOnly=true)]
		public static int? VectorCmp(object par281, object par282)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorCombine

		[Sql.Function(Name="public.vector_combine", ServerSideOnly=true)]
		public static object VectorCombine(object par284, object par285)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorConcat

		[Sql.Function(Name="public.vector_concat", ServerSideOnly=true)]
		public static object VectorConcat(object par287, object par288)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorDims

		[Sql.Function(Name="public.vector_dims", ServerSideOnly=true)]
		public static int? VectorDims(object par292)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorEq

		[Sql.Function(Name="public.vector_eq", ServerSideOnly=true)]
		public static bool? VectorEq(object par294, object par295)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorGe

		[Sql.Function(Name="public.vector_ge", ServerSideOnly=true)]
		public static bool? VectorGe(object par297, object par298)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorGt

		[Sql.Function(Name="public.vector_gt", ServerSideOnly=true)]
		public static bool? VectorGt(object par300, object par301)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorIn

		[Sql.Function(Name="public.vector_in", ServerSideOnly=true)]
		public static object VectorIn(object par303, int? par304, int? par305)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorL2SquaredDistance

		[Sql.Function(Name="public.vector_l2_squared_distance", ServerSideOnly=true)]
		public static double? VectorL2SquaredDistance(object par307, object par308)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorLe

		[Sql.Function(Name="public.vector_le", ServerSideOnly=true)]
		public static bool? VectorLe(object par310, object par311)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorLt

		[Sql.Function(Name="public.vector_lt", ServerSideOnly=true)]
		public static bool? VectorLt(object par313, object par314)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorMul

		[Sql.Function(Name="public.vector_mul", ServerSideOnly=true)]
		public static object VectorMul(object par316, object par317)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorNe

		[Sql.Function(Name="public.vector_ne", ServerSideOnly=true)]
		public static bool? VectorNe(object par319, object par320)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorNegativeInnerProduct

		[Sql.Function(Name="public.vector_negative_inner_product", ServerSideOnly=true)]
		public static double? VectorNegativeInnerProduct(object par322, object par323)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorNorm

		[Sql.Function(Name="public.vector_norm", ServerSideOnly=true)]
		public static double? VectorNorm(object par325)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorOut

		[Sql.Function(Name="public.vector_out", ServerSideOnly=true)]
		public static object VectorOut(object par327)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorRecv

		[Sql.Function(Name="public.vector_recv", ServerSideOnly=true)]
		public static object VectorRecv(object par329, int? par330, int? par331)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorSend

		[Sql.Function(Name="public.vector_send", ServerSideOnly=true)]
		public static byte[] VectorSend(object par333)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorSphericalDistance

		[Sql.Function(Name="public.vector_spherical_distance", ServerSideOnly=true)]
		public static double? VectorSphericalDistance(object par335, object par336)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorSub

		[Sql.Function(Name="public.vector_sub", ServerSideOnly=true)]
		public static object VectorSub(object par338, object par339)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorToFloat4

		[Sql.Function(Name="public.vector_to_float4", ServerSideOnly=true)]
		public static object VectorToFloat4(object par341, int? par342, bool? par343)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorToHalfvec

		[Sql.Function(Name="public.vector_to_halfvec", ServerSideOnly=true)]
		public static object VectorToHalfvec(object par345, int? par346, bool? par347)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorToSparsevec

		[Sql.Function(Name="public.vector_to_sparsevec", ServerSideOnly=true)]
		public static object VectorToSparsevec(object par349, int? par350, bool? par351)
		{
			throw new InvalidOperationException();
		}

		#endregion

		#region VectorTypmodIn

		[Sql.Function(Name="public.vector_typmod_in", ServerSideOnly=true)]
		public static int? VectorTypmodIn(object par353)
		{
			throw new InvalidOperationException();
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Category Find(this ITable<Category> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static CategorySsmMapping Find(this ITable<CategorySsmMapping> table, int SeasonStageId, int CategoryId)
		{
			return table.FirstOrDefault(t =>
				t.SeasonStageId == SeasonStageId &&
				t.CategoryId    == CategoryId);
		}

		public static CategoryStageMapping Find(this ITable<CategoryStageMapping> table, int StageId, int CategoryId)
		{
			return table.FirstOrDefault(t =>
				t.StageId    == StageId &&
				t.CategoryId == CategoryId);
		}

		public static EFMigrationsHistory Find(this ITable<EFMigrationsHistory> table, string MigrationId)
		{
			return table.FirstOrDefault(t =>
				t.MigrationId == MigrationId);
		}

		public static Season Find(this ITable<Season> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static SeasonStageMapping Find(this ITable<SeasonStageMapping> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Stage Find(this ITable<Stage> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}
