//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace MatchCentre
{
	/// <summary>
	/// Database       : matchCentredb
	/// Data Source    : tcp://localhost:51640
	/// Server Version : 17.10 (Debian 17.10-1.pgdg12+1)
	/// </summary>
	public partial class db : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<EFMigrationsHistory>    EFMigrationsHistories   { get { return this.GetTable<EFMigrationsHistory>(); } }
		public ITable<Fixture>                Fixtures                { get { return this.GetTable<Fixture>(); } }
		public ITable<FixtureCategoryMapping> FixtureCategoryMappings { get { return this.GetTable<FixtureCategoryMapping>(); } }
		public ITable<FixtureComment>         FixtureComments         { get { return this.GetTable<FixtureComment>(); } }
		public ITable<FixtureStat>            FixtureStats            { get { return this.GetTable<FixtureStat>(); } }
		public ITable<RankingTemplate>        RankingTemplates        { get { return this.GetTable<RankingTemplate>(); } }

		#endregion

		partial void InitMappingSchema()
		{
		}

		#region .ctor

		public db()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public db(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public db(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public db(DataOptions<db> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion

		#region Table Functions

		#region SearchFixtures

		[Sql.TableFunction(Schema="public", Name="search_fixtures")]
		public ITable<SearchFixturesResult> SearchFixtures(int? pSeasonStageId, int? pTeamId, int? pTeamId2, int? pCategoryId, DateTime? pStartDate, DateTime? pEndDate, int? pStartRound, int? pToRound, int? pHasScore, bool? pIsComplete, int? pOmittedId)
		{
			return this.TableFromExpression(() => SearchFixtures(pSeasonStageId, pTeamId, pTeamId2, pCategoryId, pStartDate, pEndDate, pStartRound, pToRound, pHasScore, pIsComplete, pOmittedId));
		}

		public partial class SearchFixturesResult
		{
			[Column("round")      ] public int?      Round       { get; set; }
			[Column("is_awarded") ] public bool?     Is_awarded  { get; set; }
			[Column("season_year")] public int?      Season_year { get; set; }
			[Column("id")         ] public int?      Id          { get; set; }
			[Column("is_complete")] public bool?     Is_complete { get; set; }
			[Column("has_videos") ] public bool?     Has_videos  { get; set; }
			[Column("home_id")    ] public int?      Home_id     { get; set; }
			[Column("away_id")    ] public int?      Away_id     { get; set; }
			[Column("p_time")     ] public DateTime? P_time      { get; set; }
			[Column("full_time")  ] public string    Full_time   { get; set; }
		}

		#endregion

		#endregion
	}

	[Table(Schema="public", Name="__EFMigrationsHistory")]
	public partial class EFMigrationsHistory
	{
		[PrimaryKey, NotNull] public string MigrationId    { get; set; } // character varying(150)
		[Column,     NotNull] public string ProductVersion { get; set; } // character varying(32)
	}

	[Table(Schema="public", Name="Fixture")]
	public partial class Fixture
	{
		[Column(),                      PrimaryKey,  Identity] public int             Id                       { get; set; } // integer
		[Column(),                      NotNull              ] public int             SofascoreId              { get; set; } // integer
		[Column(),                      NotNull              ] public int             HomeId                   { get; set; } // integer
		[Column(),                      NotNull              ] public int             AwayId                   { get; set; } // integer
		[Column(),                         Nullable          ] public string          Machine                  { get; set; } // text
		[Column(),                         Nullable          ] public bool?           IsFriendly               { get; set; } // boolean
		[Column(),                         Nullable          ] public string          Weather                  { get; set; } // text
		[Column(),                         Nullable          ] public string          Stadium                  { get; set; } // text
		[Column(),                         Nullable          ] public int?            Attendance               { get; set; } // integer
		[Column(),                         Nullable          ] public string          Referee                  { get; set; } // text
		[Column(),                         Nullable          ] public string          RefereeStats             { get; set; } // text
		[Column(),                      NotNull              ] public DateTimeOffset  Time                     { get; set; } // timestamp (6) with time zone
		[Column(),                         Nullable          ] public DateTimeOffset? CreatedDate              { get; set; } // timestamp (6) with time zone
		[Column(),                         Nullable          ] public DateTimeOffset? AutoTime                 { get; set; } // timestamp (6) with time zone
		[Column(),                      NotNull              ] public int             SeasonStageId            { get; set; } // integer
		[Column(),                         Nullable          ] public string          HalfTime                 { get; set; } // text
		[Column(),                         Nullable          ] public string          FullTime                 { get; set; } // text
		[Column(),                         Nullable          ] public string          ExtraTime                { get; set; } // text
		[Column(),                         Nullable          ] public string          PK                       { get; set; } // text
		[Column(),                         Nullable          ] public string          TimeElapsed              { get; set; } // text
		[Column(),                         Nullable          ] public string          LiveScore                { get; set; } // text
		[Column(),                         Nullable          ] public string          AutoUrl                  { get; set; } // text
		[Column(),                      NotNull              ] public bool            IsComplete               { get; set; } // boolean
		[Column(),                      NotNull              ] public bool            AutoComplete             { get; set; } // boolean
		[Column(),                      NotNull              ] public string          Status                   { get; set; } // character varying(10)
		[Column(),                         Nullable          ] public string          GoalUrl                  { get; set; } // text
		[Column(),                      NotNull              ] public bool            IsScraping               { get; set; } // boolean
		[Column(),                         Nullable          ] public string          Incidents                { get; set; } // text
		[Column(),                         Nullable          ] public bool?           UpdatedStat              { get; set; } // boolean
		[Column(),                         Nullable          ] public bool?           UpdatedFixtureStats      { get; set; } // boolean
		[Column(),                         Nullable          ] public bool?           UpdatedMissingPlayers    { get; set; } // boolean
		[Column(),                         Nullable          ] public bool?           UpdatedLiveMatch         { get; set; } // boolean
		[Column(),                         Nullable          ] public bool?           UpdatedProbableLineup    { get; set; } // boolean
		[Column(),                         Nullable          ] public bool?           UpdatedProbableLineup404 { get; set; } // boolean
		[Column(),                      NotNull              ] public bool            UpdatedComment           { get; set; } // boolean
		[Column(),                         Nullable          ] public bool?           RunSquawkaLive           { get; set; } // boolean
		[Column(),                         Nullable          ] public bool?           RunGoalLive              { get; set; } // boolean
		[Column(),                         Nullable          ] public string          ProbableLineup           { get; set; } // text
		[Column(),                      NotNull              ] public bool            HasVideos                { get; set; } // boolean
		[Column(),                         Nullable          ] public string          LiveTV                   { get; set; } // text
		[Column(),                         Nullable          ] public int?            MinuteExpanded           { get; set; } // integer
		[Column(),                      NotNull              ] public int             Round                    { get; set; } // integer
		[Column(),                      NotNull              ] public bool            IsAwarded                { get; set; } // boolean
		[Column("Away_AerielWon"),      NotNull              ] public double          AwayAerielWon            { get; set; } // double precision
		[Column("Away_AggressionR"),    NotNull              ] public int             AwayAggressionR          { get; set; } // integer
		[Column("Away_AggressionY"),    NotNull              ] public int             AwayAggressionY          { get; set; } // integer
		[Column("Away_Coach"),             Nullable          ] public string          AwayCoach                { get; set; } // text
		[Column("Away_Corner"),         NotNull              ] public int             AwayCorner               { get; set; } // integer
		[Column("Away_Formation"),         Nullable          ] public string          AwayFormation            { get; set; } // text
		[Column("Away_MissingPlayers"),    Nullable          ] public string          AwayMissingPlayers       { get; set; } // text
		[Column("Away_PassAccuracy"),   NotNull              ] public double          AwayPassAccuracy         { get; set; } // double precision
		[Column("Away_Possession"),     NotNull              ] public double          AwayPossession           { get; set; } // double precision
		[Column("Away_Rating"),         NotNull              ] public double          AwayRating               { get; set; } // double precision
		[Column("Away_Shots"),          NotNull              ] public int             AwayShots                { get; set; } // integer
		[Column("Away_ShotsGraph"),        Nullable          ] public string          AwayShotsGraph           { get; set; } // text
		[Column("Away_ShotsOnTarget"),  NotNull              ] public int             AwayShotsOnTarget        { get; set; } // integer
		[Column("Away_ThrowIns"),       NotNull              ] public int             AwayThrowIns             { get; set; } // integer
		[Column("Home_AerielWon"),      NotNull              ] public double          HomeAerielWon            { get; set; } // double precision
		[Column("Home_AggressionR"),    NotNull              ] public int             HomeAggressionR          { get; set; } // integer
		[Column("Home_AggressionY"),    NotNull              ] public int             HomeAggressionY          { get; set; } // integer
		[Column("Home_Coach"),             Nullable          ] public string          HomeCoach                { get; set; } // text
		[Column("Home_Corner"),         NotNull              ] public int             HomeCorner               { get; set; } // integer
		[Column("Home_Formation"),         Nullable          ] public string          HomeFormation            { get; set; } // text
		[Column("Home_MissingPlayers"),    Nullable          ] public string          HomeMissingPlayers       { get; set; } // text
		[Column("Home_PassAccuracy"),   NotNull              ] public double          HomePassAccuracy         { get; set; } // double precision
		[Column("Home_Possession"),     NotNull              ] public double          HomePossession           { get; set; } // double precision
		[Column("Home_Rating"),         NotNull              ] public double          HomeRating               { get; set; } // double precision
		[Column("Home_Shots"),          NotNull              ] public int             HomeShots                { get; set; } // integer
		[Column("Home_ShotsGraph"),        Nullable          ] public string          HomeShotsGraph           { get; set; } // text
		[Column("Home_ShotsOnTarget"),  NotNull              ] public int             HomeShotsOnTarget        { get; set; } // integer
		[Column("Home_ThrowIns"),       NotNull              ] public int             HomeThrowIns             { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_Fixture_Category_Mapping_Fixture_FixtureId_BackReference (public.Fixture_Category_Mapping)
		/// </summary>
		[Association(ThisKey=nameof(Id), OtherKey=nameof(MatchCentre.FixtureCategoryMapping.FixtureId), CanBeNull=true)]
		public IEnumerable<FixtureCategoryMapping> CategoryMappingFixtureIds { get; set; }

		/// <summary>
		/// FK_FixtureComment_Fixture_FixtureId_BackReference (public.FixtureComment)
		/// </summary>
		[Association(ThisKey=nameof(Id), OtherKey=nameof(MatchCentre.FixtureComment.FixtureId), CanBeNull=true)]
		public IEnumerable<FixtureComment> FixtureCommentFixtureIds { get; set; }

		/// <summary>
		/// FK_FixtureStats_Fixture_FixtureId_BackReference (public.FixtureStats)
		/// </summary>
		[Association(ThisKey=nameof(Id), OtherKey=nameof(MatchCentre.FixtureStat.FixtureId), CanBeNull=true)]
		public IEnumerable<FixtureStat> FixtureStatsFixtureIds { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="Fixture_Category_Mapping")]
	public partial class FixtureCategoryMapping
	{
		[PrimaryKey, Identity] public int Id         { get; set; } // integer
		[Column,     NotNull ] public int CategoryId { get; set; } // integer
		[Column,     NotNull ] public int FixtureId  { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_Fixture_Category_Mapping_Fixture_FixtureId (public.Fixture)
		/// </summary>
		[Association(ThisKey=nameof(FixtureId), OtherKey=nameof(MatchCentre.Fixture.Id), CanBeNull=false)]
		public Fixture Fixture { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="FixtureComment")]
	public partial class FixtureComment
	{
		[PrimaryKey, Identity   ] public int    Id        { get; set; } // integer
		[Column,     NotNull    ] public int    FixtureId { get; set; } // integer
		[Column,     NotNull    ] public string Min       { get; set; } // text
		[Column,     NotNull    ] public int    Team      { get; set; } // integer
		[Column,     NotNull    ] public string Text      { get; set; } // text
		[Column,        Nullable] public string Action    { get; set; } // text

		#region Associations

		/// <summary>
		/// FK_FixtureComment_Fixture_FixtureId (public.Fixture)
		/// </summary>
		[Association(ThisKey=nameof(FixtureId), OtherKey=nameof(MatchCentre.Fixture.Id), CanBeNull=false)]
		public Fixture Fixture { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="FixtureStats")]
	public partial class FixtureStat
	{
		[PrimaryKey, Identity   ] public int    Id                      { get; set; } // integer
		[Column,     NotNull    ] public int    FixtureId               { get; set; } // integer
		[Column,     NotNull    ] public int    PlayerId                { get; set; } // integer
		[Column,        Nullable] public string Position                { get; set; } // text
		[Column,        Nullable] public string PlayablePositions       { get; set; } // text
		[Column,        Nullable] public string XY                      { get; set; } // text
		[Column,        Nullable] public int?   WhoscoredFormationPlace { get; set; } // integer
		[Column,        Nullable] public int?   ShirtNumber             { get; set; } // integer
		[Column,     NotNull    ] public int    TeamOwnerId             { get; set; } // integer
		[Column,     NotNull    ] public int    SubInMinute             { get; set; } // integer
		[Column,     NotNull    ] public int    SubOutMinute            { get; set; } // integer
		[Column,     NotNull    ] public int    MinPlayed               { get; set; } // integer
		[Column,     NotNull    ] public int    Shots                   { get; set; } // integer
		[Column,     NotNull    ] public int    ShotsOnTarget           { get; set; } // integer
		[Column,     NotNull    ] public int    ShotsOffTarget          { get; set; } // integer
		[Column,     NotNull    ] public int    ShotsBlocked            { get; set; } // integer
		[Column,     NotNull    ] public int    BigChanceCreated        { get; set; } // integer
		[Column,     NotNull    ] public int    BigChanceMissed         { get; set; } // integer
		[Column,     NotNull    ] public int    Dribbles                { get; set; } // integer
		[Column,     NotNull    ] public int    DribblesWon             { get; set; } // integer
		[Column,     NotNull    ] public int    DribblesPast            { get; set; } // integer
		[Column,     NotNull    ] public int    DuelWon                 { get; set; } // integer
		[Column,     NotNull    ] public int    DuelLost                { get; set; } // integer
		[Column,     NotNull    ] public int    Fouled                  { get; set; } // integer
		[Column,     NotNull    ] public int    Fouls                   { get; set; } // integer
		[Column,     NotNull    ] public int    Offsided                { get; set; } // integer
		[Column,     NotNull    ] public int    PenaltyConceded         { get; set; } // integer
		[Column,     NotNull    ] public int    Dispossessed            { get; set; } // integer
		[Column,     NotNull    ] public int    UnsTouches              { get; set; } // integer
		[Column,     NotNull    ] public int    KeyPasses               { get; set; } // integer
		[Column,     NotNull    ] public int    AccPasses               { get; set; } // integer
		[Column,     NotNull    ] public int    Passes                  { get; set; } // integer
		[Column,     NotNull    ] public int    Crosses                 { get; set; } // integer
		[Column,     NotNull    ] public double AccCrosses              { get; set; } // double precision
		[Column,     NotNull    ] public int    LongBall                { get; set; } // integer
		[Column,     NotNull    ] public double AccLB                   { get; set; } // double precision
		[Column,     NotNull    ] public int    ThroughBall             { get; set; } // integer
		[Column,     NotNull    ] public double AccThB                  { get; set; } // double precision
		[Column,     NotNull    ] public int    TotalTackles            { get; set; } // integer
		[Column,     NotNull    ] public int    LastManTackle           { get; set; } // integer
		[Column,     NotNull    ] public int    Interceptions           { get; set; } // integer
		[Column,     NotNull    ] public int    PossessionLost          { get; set; } // integer
		[Column,     NotNull    ] public int    Clearances              { get; set; } // integer
		[Column,     NotNull    ] public int    BlockedShots            { get; set; } // integer
		[Column,     NotNull    ] public double Rating                  { get; set; } // double precision
		[Column,     NotNull    ] public bool   Motm                    { get; set; } // boolean
		[Column,        Nullable] public string KeyEvents               { get; set; } // text
		[Column,     NotNull    ] public int    AerialWon               { get; set; } // integer
		[Column,     NotNull    ] public int    AerialLost              { get; set; } // integer
		[Column,     NotNull    ] public int    GroundDuelWon           { get; set; } // integer
		[Column,     NotNull    ] public int    GroundDuelLost          { get; set; } // integer
		[Column,     NotNull    ] public int    YellowCard              { get; set; } // integer
		[Column,     NotNull    ] public int    YellowRed               { get; set; } // integer
		[Column,     NotNull    ] public int    RedCard                 { get; set; } // integer
		[Column,     NotNull    ] public int    Assist                  { get; set; } // integer
		[Column,     NotNull    ] public int    NoMatches               { get; set; } // integer
		[Column,     NotNull    ] public int    Goal                    { get; set; } // integer
		[Column,     NotNull    ] public int    OwnGoal                 { get; set; } // integer
		[Column,     NotNull    ] public int    Touches                 { get; set; } // integer
		[Column,     NotNull    ] public int    PenGoal                 { get; set; } // integer
		[Column,     NotNull    ] public int    PenWon                  { get; set; } // integer
		[Column,     NotNull    ] public int    Error2Goal              { get; set; } // integer
		[Column,     NotNull    ] public int    ClearanceOffline        { get; set; } // integer
		[Column,     NotNull    ] public int    ShotOnPost              { get; set; } // integer
		[Column,     NotNull    ] public int    PKMissed                { get; set; } // integer
		[Column,     NotNull    ] public int    PKShootoutScored        { get; set; } // integer
		[Column,     NotNull    ] public int    PKShootoutMissed        { get; set; } // integer
		[Column,     NotNull    ] public int    PKShootoutSaved         { get; set; } // integer
		[Column,     NotNull    ] public int    ThrowIns                { get; set; } // integer
		[Column,     NotNull    ] public int    GKSaves                 { get; set; } // integer
		[Column,     NotNull    ] public int    GKCatch                 { get; set; } // integer
		[Column,     NotNull    ] public int    GKPunch                 { get; set; } // integer
		[Column,     NotNull    ] public int    GKClearance             { get; set; } // integer
		[Column,     NotNull    ] public int    GKTotalSweeper          { get; set; } // integer
		[Column,     NotNull    ] public int    GKErrorLeadToAShot      { get; set; } // integer
		[Column,     NotNull    ] public int    GKSweeper               { get; set; } // integer
		[Column,     NotNull    ] public int    GKPenSaves              { get; set; } // integer
		[Column,     NotNull    ] public bool   IsCaptain               { get; set; } // boolean

		#region Associations

		/// <summary>
		/// FK_FixtureStats_Fixture_FixtureId (public.Fixture)
		/// </summary>
		[Association(ThisKey=nameof(FixtureId), OtherKey=nameof(MatchCentre.Fixture.Id), CanBeNull=false)]
		public Fixture Fixture { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="RankingTemplate")]
	public partial class RankingTemplate
	{
		[PrimaryKey(1), NotNull] public int SeasonStageId          { get; set; } // integer
		[PrimaryKey(2), NotNull] public int CategoryId             { get; set; } // integer
		[Column,        NotNull] public int Relegation             { get; set; } // integer
		[Column,        NotNull] public int RelegationPlayOff      { get; set; } // integer
		[Column,        NotNull] public int UefaC1                 { get; set; } // integer
		[Column,        NotNull] public int UefaC1Qualifiers       { get; set; } // integer
		[Column,        NotNull] public int EuropaLeagueQualifiers { get; set; } // integer
		[Column,        NotNull] public int EuropaLeague           { get; set; } // integer
		[Column,        NotNull] public int EuropaLeagueSpots      { get; set; } // integer
	}

	public static partial class TableExtensions
	{
		public static EFMigrationsHistory Find(this ITable<EFMigrationsHistory> table, string MigrationId)
		{
			return table.FirstOrDefault(t =>
				t.MigrationId == MigrationId);
		}

		public static Fixture Find(this ITable<Fixture> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static FixtureCategoryMapping Find(this ITable<FixtureCategoryMapping> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static FixtureComment Find(this ITable<FixtureComment> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static FixtureStat Find(this ITable<FixtureStat> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static RankingTemplate Find(this ITable<RankingTemplate> table, int SeasonStageId, int CategoryId)
		{
			return table.FirstOrDefault(t =>
				t.SeasonStageId == SeasonStageId &&
				t.CategoryId    == CategoryId);
		}
	}
}
