//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace TeamPlayer
{
	/// <summary>
	/// Database       : teamPlayerdb
	/// Data Source    : tcp://localhost:51640
	/// Server Version : 17.10 (Debian 17.10-1.pgdg12+1)
	/// </summary>
	public partial class db : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<EFMigrationsHistory> EFMigrationsHistories { get { return this.GetTable<EFMigrationsHistory>(); } }
		public ITable<Player>              Players               { get { return this.GetTable<Player>(); } }
		public ITable<Team>                Teams                 { get { return this.GetTable<Team>(); } }
		public ITable<TeamCategoryMapping> TeamCategoryMappings  { get { return this.GetTable<TeamCategoryMapping>(); } }
		public ITable<TeamPlayerMapping>   TeamPlayerMappings    { get { return this.GetTable<TeamPlayerMapping>(); } }

		#endregion

		partial void InitMappingSchema()
		{
		}

		#region .ctor

		public db()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public db(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public db(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public db(DataOptions<db> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="public", Name="__EFMigrationsHistory")]
	public partial class EFMigrationsHistory
	{
		[PrimaryKey, NotNull] public string MigrationId    { get; set; } // character varying(150)
		[Column,     NotNull] public string ProductVersion { get; set; } // character varying(32)
	}

	[Table(Schema="public", Name="Player")]
	public partial class Player
	{
		[PrimaryKey, Identity   ] public int             Id                          { get; set; } // integer
		[Column,     NotNull    ] public string          Name                        { get; set; } // character varying(50)
		[Column,        Nullable] public string          ShortName                   { get; set; } // text
		[Column,        Nullable] public DateTimeOffset? Birthdate                   { get; set; } // timestamp (6) with time zone
		[Column,     NotNull    ] public int             CountryId                   { get; set; } // integer
		[Column,        Nullable] public int?            CountryId2                  { get; set; } // integer
		[Column,        Nullable] public string          Height                      { get; set; } // text
		[Column,        Nullable] public string          Weight                      { get; set; } // text
		[Column,        Nullable] public int?            WhoscoredPlayerId           { get; set; } // integer
		[Column,        Nullable] public int?            SofascorePlayerId           { get; set; } // integer
		[Column,        Nullable] public int?            SquawkaPlayerId             { get; set; } // integer
		[Column,        Nullable] public int?            GoalPlayerId                { get; set; } // integer
		[Column,        Nullable] public int?            InternationalCaps           { get; set; } // integer
		[Column,        Nullable] public string          Url                         { get; set; } // text
		[Column,        Nullable] public string          TransferMkName              { get; set; } // text
		[Column,        Nullable] public string          TeamPosition                { get; set; } // text
		[Column,     NotNull    ] public decimal         PercentageGainInLast6Rounds { get; set; } // numeric
		[Column,        Nullable] public int?            FantasyOwner                { get; set; } // integer
		[Column,        Nullable] public int?            AttackIndexInLast6Rounds    { get; set; } // integer
		[Column,        Nullable] public int?            DefenseIndexInLast6Rounds   { get; set; } // integer
		[Column,        Nullable] public int?            MarketValue                 { get; set; } // integer
		[Column,        Nullable] public string          PreferredFoot               { get; set; } // text
		[Column,        Nullable] public string          SeName                      { get; set; } // text
		[Column,        Nullable] public string          SkillSets                   { get; set; } // text
		[Column,        Nullable] public DateTimeOffset? UpdatedDate                 { get; set; } // timestamp (6) with time zone
		[Column,        Nullable] public string          PictureUrl                  { get; set; } // text
		[Column,     NotNull    ] public int             PictureId                   { get; set; } // integer
		[Column,        Nullable] public string          Slug                        { get; set; } // character varying(50)

		#region Associations

		/// <summary>
		/// FK_Team_Player_Mapping_Player_PlayerId_BackReference (public.Team_Player_Mapping)
		/// </summary>
		[Association(ThisKey=nameof(Id), OtherKey=nameof(TeamPlayer.TeamPlayerMapping.PlayerId), CanBeNull=true)]
		public IEnumerable<TeamPlayerMapping> TeamMappingPlayerIds { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="Team")]
	public partial class Team
	{
		[PrimaryKey, Identity   ] public int             Id                     { get; set; } // integer
		[Column,     NotNull    ] public string          Name                   { get; set; } // character varying(50)
		[Column,     NotNull    ] public string          UefaName               { get; set; } // text
		[Column,     NotNull    ] public int             UefaRanking            { get; set; } // integer
		[Column,     NotNull    ] public int             Fame                   { get; set; } // integer
		[Column,        Nullable] public int?            SofascoreId            { get; set; } // integer
		[Column,     NotNull    ] public string          ShortName              { get; set; } // text
		[Column,        Nullable] public string          Web                    { get; set; } // text
		[Column,        Nullable] public string          AutoUrl                { get; set; } // text
		[Column,        Nullable] public string          Theme                  { get; set; } // text
		[Column,        Nullable] public string          Background             { get; set; } // text
		[Column,        Nullable] public string          TransferMarktUrl       { get; set; } // text
		[Column,        Nullable] public string          TransferMarktName      { get; set; } // text
		[Column,        Nullable] public DateTimeOffset? TransferMarkUpdateDate { get; set; } // timestamp (6) with time zone
		[Column,        Nullable] public string          Bet188                 { get; set; } // text
		[Column,        Nullable] public int?            WhoscoredId            { get; set; } // integer
		[Column,        Nullable] public int?            CountryId              { get; set; } // integer
		[Column,        Nullable] public DateTimeOffset? GoalTeamCheck          { get; set; } // timestamp (6) with time zone
		[Column,        Nullable] public DateTimeOffset? TransferMarktCheck     { get; set; } // timestamp (6) with time zone
		[Column,        Nullable] public DateTimeOffset? WSTeamCheck            { get; set; } // timestamp (6) with time zone
		[Column,        Nullable] public DateTimeOffset? SofascoreUpdate        { get; set; } // timestamp (6) with time zone
		[Column,     NotNull    ] public string          SeName                 { get; set; } // text
		[Column,        Nullable] public string          Logo                   { get; set; } // text
		[Column,        Nullable] public string          GoalName               { get; set; } // character varying(100)
		[Column,        Nullable] public string          FoxName                { get; set; } // character varying(100)
		[Column,        Nullable] public int?            GoalId                 { get; set; } // integer
		[Column,        Nullable] public string          GoalUrl                { get; set; } // character varying(200)

		#region Associations

		/// <summary>
		/// FK_Team_Category_Mapping_Team_TeamId_BackReference (public.Team_Category_Mapping)
		/// </summary>
		[Association(ThisKey=nameof(Id), OtherKey=nameof(TeamPlayer.TeamCategoryMapping.TeamId), CanBeNull=true)]
		public IEnumerable<TeamCategoryMapping> CategoryMappingTeamIds { get; set; }

		/// <summary>
		/// FK_Team_Player_Mapping_Team_TeamId_BackReference (public.Team_Player_Mapping)
		/// </summary>
		[Association(ThisKey=nameof(Id), OtherKey=nameof(TeamPlayer.TeamPlayerMapping.TeamId), CanBeNull=true)]
		public IEnumerable<TeamPlayerMapping> PlayerMappingTeamIds { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="Team_Category_Mapping")]
	public partial class TeamCategoryMapping
	{
		[PrimaryKey(1), NotNull    ] public int    CategoryId        { get; set; } // integer
		[PrimaryKey(2), NotNull    ] public int    TeamId            { get; set; } // integer
		[PrimaryKey(3), NotNull    ] public int    SeasonStageId     { get; set; } // integer
		[Column,           Nullable] public int?   Rank              { get; set; } // integer
		[Column,           Nullable] public int?   LastRank          { get; set; } // integer
		[Column,        NotNull    ] public int    W                 { get; set; } // integer
		[Column,           Nullable] public int?   D                 { get; set; } // integer
		[Column,           Nullable] public int?   L                 { get; set; } // integer
		[Column,           Nullable] public int?   GF                { get; set; } // integer
		[Column,           Nullable] public int?   GA                { get; set; } // integer
		[Column,           Nullable] public int?   GD                { get; set; } // integer
		[Column,           Nullable] public int?   Pts               { get; set; } // integer
		[Column,           Nullable] public int?   P                 { get; set; } // integer
		[Column,           Nullable] public string Forms             { get; set; } // text
		[Column,        NotNull    ] public int    HomeWinStreak     { get; set; } // integer
		[Column,        NotNull    ] public int    AwayWinStreak     { get; set; } // integer
		[Column,        NotNull    ] public int    HomeUndefeated    { get; set; } // integer
		[Column,        NotNull    ] public int    AwayUndefeated    { get; set; } // integer
		[Column,        NotNull    ] public int    HomeCleanSheet    { get; set; } // integer
		[Column,        NotNull    ] public int    AwayCleanSheet    { get; set; } // integer
		[Column,        NotNull    ] public int    HomeFailedToScore { get; set; } // integer
		[Column,        NotNull    ] public int    AwayFailedToScore { get; set; } // integer
		[Column,        NotNull    ] public int    HomeLoseStreak    { get; set; } // integer
		[Column,        NotNull    ] public int    AwayLoseStreak    { get; set; } // integer
		[Column,        NotNull    ] public int    WinStreak         { get; set; } // integer
		[Column,        NotNull    ] public int    LoseStreak        { get; set; } // integer
		[Column,        NotNull    ] public int    Undefeated        { get; set; } // integer
		[Column,        NotNull    ] public int    FailedToScore     { get; set; } // integer
		[Column,        NotNull    ] public int    HomeScore         { get; set; } // integer
		[Column,        NotNull    ] public int    AwayScore         { get; set; } // integer
		[Column,        NotNull    ] public int    TeamGoals         { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_Team_Category_Mapping_Team_TeamId (public.Team)
		/// </summary>
		[Association(ThisKey=nameof(TeamId), OtherKey=nameof(TeamPlayer.Team.Id), CanBeNull=false)]
		public Team Team { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="Team_Player_Mapping")]
	public partial class TeamPlayerMapping
	{
		[PrimaryKey(1), NotNull    ] public int    TeamId             { get; set; } // integer
		[PrimaryKey(2), NotNull    ] public int    PlayerId           { get; set; } // integer
		[PrimaryKey(3), NotNull    ] public int    SeasonStageId      { get; set; } // integer
		[Column,           Nullable] public int?   ShirtNumber        { get; set; } // integer
		[Column,        NotNull    ] public string Position           { get; set; } // text
		[Column,           Nullable] public int?   GoalShirtNumber    { get; set; } // integer
		[Column,           Nullable] public int?   SquawkaShirtNumber { get; set; } // integer
		[Column,        NotNull    ] public bool   Status             { get; set; } // boolean
		[Column,        NotNull    ] public int    Id                 { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_Team_Player_Mapping_Player_PlayerId (public.Player)
		/// </summary>
		[Association(ThisKey=nameof(PlayerId), OtherKey=nameof(TeamPlayer.Player.Id), CanBeNull=false)]
		public Player Player { get; set; }

		/// <summary>
		/// FK_Team_Player_Mapping_Team_TeamId (public.Team)
		/// </summary>
		[Association(ThisKey=nameof(TeamId), OtherKey=nameof(TeamPlayer.Team.Id), CanBeNull=false)]
		public Team Team { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static EFMigrationsHistory Find(this ITable<EFMigrationsHistory> table, string MigrationId)
		{
			return table.FirstOrDefault(t =>
				t.MigrationId == MigrationId);
		}

		public static Player Find(this ITable<Player> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Team Find(this ITable<Team> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static TeamCategoryMapping Find(this ITable<TeamCategoryMapping> table, int CategoryId, int TeamId, int SeasonStageId)
		{
			return table.FirstOrDefault(t =>
				t.CategoryId    == CategoryId &&
				t.TeamId        == TeamId     &&
				t.SeasonStageId == SeasonStageId);
		}

		public static TeamPlayerMapping Find(this ITable<TeamPlayerMapping> table, int TeamId, int PlayerId, int SeasonStageId)
		{
			return table.FirstOrDefault(t =>
				t.TeamId        == TeamId   &&
				t.PlayerId      == PlayerId &&
				t.SeasonStageId == SeasonStageId);
		}
	}
}
