// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eSport.MatchCentre.API.Infrastructure;

#nullable disable

namespace eSport.MatchCentre.API.Infrastructure.Migrations
{
    [DbContext(typeof(FixtureContext))]
    partial class FixtureContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eSport.MatchCentre.API.Models.Fixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Attendance")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoComplete")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AutoTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AutoUrl")
                        .HasColumnType("text");

                    b.Property<int>("AwayId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtraTime")
                        .HasColumnType("text");

                    b.Property<string>("FullTime")
                        .HasColumnType("text");

                    b.Property<string>("GoalUrl")
                        .HasColumnType("text");

                    b.Property<string>("HalfTime")
                        .HasColumnType("text");

                    b.Property<bool>("HasVideos")
                        .HasColumnType("boolean");

                    b.Property<int>("HomeId")
                        .HasColumnType("integer");

                    b.Property<string>("Incidents")
                        .HasColumnType("text");

                    b.Property<bool>("IsAwarded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsFriendly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsScraping")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTopMatch")
                        .HasColumnType("boolean");

                    b.Property<string>("LiveScore")
                        .HasColumnType("text");

                    b.Property<string>("LiveTV")
                        .HasColumnType("text");

                    b.Property<string>("Machine")
                        .HasColumnType("text");

                    b.Property<int?>("MinuteExpanded")
                        .HasColumnType("integer");

                    b.Property<string>("PK")
                        .HasColumnType("text");

                    b.Property<string>("ProbableLineup")
                        .HasColumnType("text");

                    b.Property<string>("Referee")
                        .HasColumnType("text");

                    b.Property<string>("RefereeStats")
                        .HasColumnType("text");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<bool?>("RunGoalLive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RunSquawkaLive")
                        .HasColumnType("boolean");

                    b.Property<int>("SeasonStageId")
                        .HasColumnType("integer");

                    b.Property<int>("SofascoreId")
                        .HasColumnType("integer");

                    b.Property<string>("Stadium")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimeElapsed")
                        .HasColumnType("text");

                    b.Property<bool>("UpdatedComment")
                        .HasColumnType("boolean");

                    b.Property<bool?>("UpdatedFixtureStats")
                        .HasColumnType("boolean");

                    b.Property<bool?>("UpdatedLiveMatch")
                        .HasColumnType("boolean");

                    b.Property<bool?>("UpdatedMissingPlayers")
                        .HasColumnType("boolean");

                    b.Property<bool?>("UpdatedProbableLineup")
                        .HasColumnType("boolean");

                    b.Property<bool?>("UpdatedProbableLineup404")
                        .HasColumnType("boolean");

                    b.Property<bool?>("UpdatedStat")
                        .HasColumnType("boolean");

                    b.Property<string>("Weather")
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Away", "eSport.MatchCentre.API.Models.Fixture.Away#Stats", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("AerielWon")
                                .HasColumnType("double precision");

                            b1.Property<int>("AggressionR")
                                .HasColumnType("integer");

                            b1.Property<int>("AggressionY")
                                .HasColumnType("integer");

                            b1.Property<string>("Coach")
                                .HasColumnType("text");

                            b1.Property<int>("Corner")
                                .HasColumnType("integer");

                            b1.Property<string>("Formation")
                                .HasColumnType("text");

                            b1.Property<string>("MissingPlayers")
                                .HasColumnType("text");

                            b1.Property<double>("PassAccuracy")
                                .HasColumnType("double precision");

                            b1.Property<double>("Possession")
                                .HasColumnType("double precision");

                            b1.Property<double>("Rating")
                                .HasColumnType("double precision");

                            b1.Property<int>("Shots")
                                .HasColumnType("integer");

                            b1.Property<string>("ShotsGraph")
                                .HasColumnType("text");

                            b1.Property<int>("ShotsOnTarget")
                                .HasColumnType("integer");

                            b1.Property<int>("ThrowIns")
                                .HasColumnType("integer");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Home", "eSport.MatchCentre.API.Models.Fixture.Home#Stats", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("AerielWon")
                                .HasColumnType("double precision");

                            b1.Property<int>("AggressionR")
                                .HasColumnType("integer");

                            b1.Property<int>("AggressionY")
                                .HasColumnType("integer");

                            b1.Property<string>("Coach")
                                .HasColumnType("text");

                            b1.Property<int>("Corner")
                                .HasColumnType("integer");

                            b1.Property<string>("Formation")
                                .HasColumnType("text");

                            b1.Property<string>("MissingPlayers")
                                .HasColumnType("text");

                            b1.Property<double>("PassAccuracy")
                                .HasColumnType("double precision");

                            b1.Property<double>("Possession")
                                .HasColumnType("double precision");

                            b1.Property<double>("Rating")
                                .HasColumnType("double precision");

                            b1.Property<int>("Shots")
                                .HasColumnType("integer");

                            b1.Property<string>("ShotsGraph")
                                .HasColumnType("text");

                            b1.Property<int>("ShotsOnTarget")
                                .HasColumnType("integer");

                            b1.Property<int>("ThrowIns")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.ToTable("Fixture", (string)null);
                });

            modelBuilder.Entity("eSport.MatchCentre.API.Models.FixtureCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("FixtureId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.ToTable("Fixture_Category_Mapping", (string)null);
                });

            modelBuilder.Entity("eSport.MatchCentre.API.Models.FixtureComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<int>("FixtureId")
                        .HasColumnType("integer");

                    b.Property<string>("Min")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Team")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.ToTable("FixtureComment");
                });

            modelBuilder.Entity("eSport.MatchCentre.API.Models.FixtureStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AccCrosses")
                        .HasColumnType("double precision");

                    b.Property<double>("AccLB")
                        .HasColumnType("double precision");

                    b.Property<int>("AccPasses")
                        .HasColumnType("integer");

                    b.Property<double>("AccThB")
                        .HasColumnType("double precision");

                    b.Property<int>("AerialLost")
                        .HasColumnType("integer");

                    b.Property<int>("AerialWon")
                        .HasColumnType("integer");

                    b.Property<int>("Assist")
                        .HasColumnType("integer");

                    b.Property<int>("BigChanceCreated")
                        .HasColumnType("integer");

                    b.Property<int>("BigChanceMissed")
                        .HasColumnType("integer");

                    b.Property<int>("BlockedShots")
                        .HasColumnType("integer");

                    b.Property<int>("ClearanceOffline")
                        .HasColumnType("integer");

                    b.Property<int>("Clearances")
                        .HasColumnType("integer");

                    b.Property<int>("Crosses")
                        .HasColumnType("integer");

                    b.Property<int>("Dispossessed")
                        .HasColumnType("integer");

                    b.Property<int>("Dribbles")
                        .HasColumnType("integer");

                    b.Property<int>("DribblesPast")
                        .HasColumnType("integer");

                    b.Property<int>("DribblesWon")
                        .HasColumnType("integer");

                    b.Property<int>("DuelLost")
                        .HasColumnType("integer");

                    b.Property<int>("DuelWon")
                        .HasColumnType("integer");

                    b.Property<int>("Error2Goal")
                        .HasColumnType("integer");

                    b.Property<int>("FixtureId")
                        .HasColumnType("integer");

                    b.Property<int>("Fouled")
                        .HasColumnType("integer");

                    b.Property<int>("Fouls")
                        .HasColumnType("integer");

                    b.Property<int>("GKCatch")
                        .HasColumnType("integer");

                    b.Property<int>("GKClearance")
                        .HasColumnType("integer");

                    b.Property<int>("GKErrorLeadToAShot")
                        .HasColumnType("integer");

                    b.Property<int>("GKPenSaves")
                        .HasColumnType("integer");

                    b.Property<int>("GKPunch")
                        .HasColumnType("integer");

                    b.Property<int>("GKSaves")
                        .HasColumnType("integer");

                    b.Property<int>("GKSweeper")
                        .HasColumnType("integer");

                    b.Property<int>("GKTotalSweeper")
                        .HasColumnType("integer");

                    b.Property<int>("Goal")
                        .HasColumnType("integer");

                    b.Property<int>("GroundDuelLost")
                        .HasColumnType("integer");

                    b.Property<int>("GroundDuelWon")
                        .HasColumnType("integer");

                    b.Property<int>("Interceptions")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyEvents")
                        .HasColumnType("text");

                    b.Property<int>("KeyPasses")
                        .HasColumnType("integer");

                    b.Property<int>("LastManTackle")
                        .HasColumnType("integer");

                    b.Property<int>("LongBall")
                        .HasColumnType("integer");

                    b.Property<int>("MinPlayed")
                        .HasColumnType("integer");

                    b.Property<bool>("Motm")
                        .HasColumnType("boolean");

                    b.Property<int>("NoMatches")
                        .HasColumnType("integer");

                    b.Property<int>("Offsided")
                        .HasColumnType("integer");

                    b.Property<int>("OwnGoal")
                        .HasColumnType("integer");

                    b.Property<int>("PKMissed")
                        .HasColumnType("integer");

                    b.Property<int>("PKShootoutMissed")
                        .HasColumnType("integer");

                    b.Property<int>("PKShootoutSaved")
                        .HasColumnType("integer");

                    b.Property<int>("PKShootoutScored")
                        .HasColumnType("integer");

                    b.Property<int>("Passes")
                        .HasColumnType("integer");

                    b.Property<int>("PenGoal")
                        .HasColumnType("integer");

                    b.Property<int>("PenWon")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltyConceded")
                        .HasColumnType("integer");

                    b.Property<string>("PlayablePositions")
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<int>("PossessionLost")
                        .HasColumnType("integer");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("RedCard")
                        .HasColumnType("integer");

                    b.Property<int?>("ShirtNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ShotOnPost")
                        .HasColumnType("integer");

                    b.Property<int>("Shots")
                        .HasColumnType("integer");

                    b.Property<int>("ShotsBlocked")
                        .HasColumnType("integer");

                    b.Property<int>("ShotsOffTarget")
                        .HasColumnType("integer");

                    b.Property<int>("ShotsOnTarget")
                        .HasColumnType("integer");

                    b.Property<int>("SubInMinute")
                        .HasColumnType("integer");

                    b.Property<int>("SubOutMinute")
                        .HasColumnType("integer");

                    b.Property<int>("TeamOwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("ThroughBall")
                        .HasColumnType("integer");

                    b.Property<int>("ThrowIns")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTackles")
                        .HasColumnType("integer");

                    b.Property<int>("Touches")
                        .HasColumnType("integer");

                    b.Property<int>("UnsTouches")
                        .HasColumnType("integer");

                    b.Property<int?>("WhoscoredFormationPlace")
                        .HasColumnType("integer");

                    b.Property<string>("XY")
                        .HasColumnType("text");

                    b.Property<int>("YellowCard")
                        .HasColumnType("integer");

                    b.Property<int>("YellowRed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.ToTable("FixtureStats", (string)null);
                });

            modelBuilder.Entity("eSport.MatchCentre.API.Models.RankingTemplate", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonStageId")
                        .HasColumnType("integer");

                    b.Property<int>("EuropaLeague")
                        .HasColumnType("integer");

                    b.Property<int>("EuropaLeagueQualifiers")
                        .HasColumnType("integer");

                    b.Property<int>("EuropaLeagueSpots")
                        .HasColumnType("integer");

                    b.Property<int>("Relegation")
                        .HasColumnType("integer");

                    b.Property<int>("RelegationPlayOff")
                        .HasColumnType("integer");

                    b.Property<int>("UefaC1")
                        .HasColumnType("integer");

                    b.Property<int>("UefaC1Qualifiers")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId", "SeasonStageId");

                    b.ToTable("RankingTemplate", (string)null);
                });

            modelBuilder.Entity("eSport.MatchCentre.API.Models.FixtureCategory", b =>
                {
                    b.HasOne("eSport.MatchCentre.API.Models.Fixture", "Fixture")
                        .WithMany("FixtureCategories")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("eSport.MatchCentre.API.Models.FixtureComment", b =>
                {
                    b.HasOne("eSport.MatchCentre.API.Models.Fixture", "Fixture")
                        .WithMany("FixtureComments")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("eSport.MatchCentre.API.Models.FixtureStat", b =>
                {
                    b.HasOne("eSport.MatchCentre.API.Models.Fixture", "Fixture")
                        .WithMany("FixtureStats")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("eSport.MatchCentre.API.Models.Fixture", b =>
                {
                    b.Navigation("FixtureCategories");

                    b.Navigation("FixtureComments");

                    b.Navigation("FixtureStats");
                });
#pragma warning restore 612, 618
        }
    }
}
