// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eSport.TeamPlayer.API.Infrastructure;

#nullable disable

namespace eSport.TeamPlayer.API.Infrastructure.Migrations
{
    [DbContext(typeof(TeamPlayerContext))]
    partial class TeamPlayerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eSport.TeamPlayer.API.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttackIndexInLast6Rounds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<int?>("CountryId2")
                        .HasColumnType("integer");

                    b.Property<int?>("DefenseIndexInLast6Rounds")
                        .HasColumnType("integer");

                    b.Property<int?>("FantasyOwner")
                        .HasColumnType("integer");

                    b.Property<int?>("GoalPlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Height")
                        .HasColumnType("text");

                    b.Property<int?>("InternationalCaps")
                        .HasColumnType("integer");

                    b.Property<int?>("MarketValue")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PercentageGainInLast6Rounds")
                        .HasColumnType("numeric");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("PreferredFoot")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<string>("SkillSets")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.Property<int?>("SofascorePlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("SquawkaPlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamPosition")
                        .HasColumnType("text");

                    b.Property<string>("TransferMkName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("Weight")
                        .HasColumnType("text");

                    b.Property<int?>("WhoscoredPlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("eSport.TeamPlayer.API.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AutoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Background")
                        .HasColumnType("text");

                    b.Property<string>("Bet188")
                        .HasColumnType("text");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<int>("Fame")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GoalTeamCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SofascoreId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SofascoreUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Theme")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TransferMarkUpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TransferMarktCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransferMarktName")
                        .HasColumnType("text");

                    b.Property<string>("TransferMarktUrl")
                        .HasColumnType("text");

                    b.Property<string>("UefaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UefaRanking")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("WSTeamCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Web")
                        .HasColumnType("text");

                    b.Property<int?>("WhoscoredId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("eSport.TeamPlayer.API.Models.TeamCategory", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonStageId")
                        .HasColumnType("integer");

                    b.Property<int>("AwayCleanSheet")
                        .HasColumnType("integer");

                    b.Property<int>("AwayFailedToScore")
                        .HasColumnType("integer");

                    b.Property<int>("AwayLoseStreak")
                        .HasColumnType("integer");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<int>("AwayUndefeated")
                        .HasColumnType("integer");

                    b.Property<int>("AwayWinStreak")
                        .HasColumnType("integer");

                    b.Property<int?>("D")
                        .HasColumnType("integer");

                    b.Property<int>("FailedToScore")
                        .HasColumnType("integer");

                    b.Property<string>("Forms")
                        .HasColumnType("text");

                    b.Property<int?>("GA")
                        .HasColumnType("integer");

                    b.Property<int?>("GD")
                        .HasColumnType("integer");

                    b.Property<int?>("GF")
                        .HasColumnType("integer");

                    b.Property<int>("HomeCleanSheet")
                        .HasColumnType("integer");

                    b.Property<int>("HomeFailedToScore")
                        .HasColumnType("integer");

                    b.Property<int>("HomeLoseStreak")
                        .HasColumnType("integer");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<int>("HomeUndefeated")
                        .HasColumnType("integer");

                    b.Property<int>("HomeWinStreak")
                        .HasColumnType("integer");

                    b.Property<int?>("L")
                        .HasColumnType("integer");

                    b.Property<int?>("LastRank")
                        .HasColumnType("integer");

                    b.Property<int>("LoseStreak")
                        .HasColumnType("integer");

                    b.Property<int?>("P")
                        .HasColumnType("integer");

                    b.Property<int?>("Pts")
                        .HasColumnType("integer");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("TeamGoals")
                        .HasColumnType("integer");

                    b.Property<int>("Undefeated")
                        .HasColumnType("integer");

                    b.Property<int>("W")
                        .HasColumnType("integer");

                    b.Property<int>("WinStreak")
                        .HasColumnType("integer");

                    b.HasKey("TeamId", "CategoryId", "SeasonStageId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Team_Category_Mapping", (string)null);
                });

            modelBuilder.Entity("eSport.TeamPlayer.API.Models.TeamPlayer", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonStageId")
                        .HasColumnType("integer");

                    b.Property<int?>("GoalShirtNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ShirtNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("SquawkaShirtNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("TeamId", "PlayerId", "SeasonStageId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Team_Player_Mapping", (string)null);
                });

            modelBuilder.Entity("eSport.TeamPlayer.API.Models.TeamCategory", b =>
                {
                    b.HasOne("eSport.TeamPlayer.API.Models.Team", "Team")
                        .WithMany("TeamCategories")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("eSport.TeamPlayer.API.Models.TeamPlayer", b =>
                {
                    b.HasOne("eSport.TeamPlayer.API.Models.Player", "Player")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSport.TeamPlayer.API.Models.Team", "Team")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("eSport.TeamPlayer.API.Models.Player", b =>
                {
                    b.Navigation("TeamPlayers");
                });

            modelBuilder.Entity("eSport.TeamPlayer.API.Models.Team", b =>
                {
                    b.Navigation("TeamCategories");

                    b.Navigation("TeamPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
