// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using eSport.Catalog.API.Infrastructure;

#nullable disable

namespace eSport.Catalog.API.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogContext))]
    partial class CatalogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eSport.Catalog.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Coefficient")
                        .HasColumnType("double precision");

                    b.Property<string>("CountryCSS")
                        .HasColumnType("text");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(384)");

                    b.Property<int?>("EuropaLeague")
                        .HasColumnType("integer");

                    b.Property<int?>("EuropaLeagueQualifiers")
                        .HasColumnType("integer");

                    b.Property<int>("FromMonth")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<bool>("IncludeInTopMenu")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsData")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTournament")
                        .HasColumnType("boolean");

                    b.Property<int?>("LeagueLogo")
                        .HasColumnType("integer");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("text");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PageSize")
                        .HasColumnType("integer");

                    b.Property<int>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("PictureId")
                        .HasColumnType("integer");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<int?>("Relegation")
                        .HasColumnType("integer");

                    b.Property<int?>("RelegationPlayOff")
                        .HasColumnType("integer");

                    b.Property<int>("Rounds")
                        .HasColumnType("integer");

                    b.Property<string>("SeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("ShowOnHomePage")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ShowStanding")
                        .HasColumnType("boolean");

                    b.Property<int>("SofaScoreId")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<int>("ToMonth")
                        .HasColumnType("integer");

                    b.Property<string>("Transfermarkt")
                        .HasColumnType("text");

                    b.Property<int?>("UefaC1")
                        .HasColumnType("integer");

                    b.Property<int?>("UefaC1Qualifiers")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("eSport.Catalog.API.Models.CategoryStage", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.Property<int>("FixtureCount")
                        .HasColumnType("integer");

                    b.Property<int>("FromDateUseYearPart")
                        .HasColumnType("integer");

                    b.Property<int>("FromMonth")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ToDateUseYearPart")
                        .HasColumnType("integer");

                    b.Property<int>("ToMonth")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId", "StageId");

                    b.HasIndex("StageId");

                    b.ToTable("Category_Stage_Mapping", (string)null);
                });

            modelBuilder.Entity("eSport.Catalog.API.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Year2")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Season", (string)null);
                });

            modelBuilder.Entity("eSport.Catalog.API.Models.SeasonStage", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("StageId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("SeasonId", "StageId");

                    b.HasIndex("StageId");

                    b.ToTable("Season_Stage_Mapping", (string)null);
                });

            modelBuilder.Entity("eSport.Catalog.API.Models.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("C1SofascoreName")
                        .HasColumnType("text");

                    b.Property<string>("C1WhoscoredName")
                        .HasColumnType("text");

                    b.Property<string>("C3SofascoreName")
                        .HasColumnType("text");

                    b.Property<string>("C3WhoscoredName")
                        .HasColumnType("text");

                    b.Property<bool>("Display")
                        .HasColumnType("boolean");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("EuroSofascoreName")
                        .HasColumnType("text");

                    b.Property<string>("EuroWhoscoredName")
                        .HasColumnType("text");

                    b.Property<bool?>("GroupStage")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("NoOfMatches")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<string>("WCSofascoreName")
                        .HasColumnType("text");

                    b.Property<string>("WCWhoscoredName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Stage", (string)null);
                });

            modelBuilder.Entity("eSport.Catalog.API.Models.CategoryStage", b =>
                {
                    b.HasOne("eSport.Catalog.API.Models.Category", "Category")
                        .WithMany("CategoryStages")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSport.Catalog.API.Models.Stage", "Stage")
                        .WithMany("CategoryStages")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("eSport.Catalog.API.Models.SeasonStage", b =>
                {
                    b.HasOne("eSport.Catalog.API.Models.Season", "Season")
                        .WithMany("SeasonStages")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSport.Catalog.API.Models.Stage", "Stage")
                        .WithMany("SeasonStages")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("eSport.Catalog.API.Models.Category", b =>
                {
                    b.Navigation("CategoryStages");
                });

            modelBuilder.Entity("eSport.Catalog.API.Models.Season", b =>
                {
                    b.Navigation("SeasonStages");
                });

            modelBuilder.Entity("eSport.Catalog.API.Models.Stage", b =>
                {
                    b.Navigation("CategoryStages");

                    b.Navigation("SeasonStages");
                });
#pragma warning restore 612, 618
        }
    }
}
