schema {
  query: Query
}

type Query {
  fixture(id: Int!): [Fixture!]! @cacheControl(maxAge: 0) @cost(weight: "10")
  fixturesByLeague(
    seasonStageId: Int!
    categoryId: Int!
    startDate: DateTime!
    endDate: DateTime!
  ): [Fixture!]! @cacheControl(maxAge: 0) @cost(weight: "10")
  leaguePlayerStats(filter: LeaguePlayerStatsFilterInput!): PagedResultOfLeaguePlayerAggregateDto!
    @cacheControl(maxAge: 0)
    @cost(weight: "10")
  topLeaguePlayersStats(filter: LeaguePlayerStatsFilterInput!): TopPlayerStatsModel!
    @cacheControl(maxAge: 0)
    @cost(weight: "10")
  teamsStatsByLeague(categoryId: Int!, seasonStageId: Int!): TopTeamStatDto!
    @cacheControl(maxAge: 0)
    @cost(weight: "10")
}

type AttackingStats {
  goals: Int!
  penGoals: Int!
  assists: Int!
  shotsPerGame: Float!
  shotsOnTarget: Float!
  keyPasses: Float!
  dribbles: Float!
  fouled: Float!
  offsides: Float!
}

type DefendingStats {
  tackles: Float!
  interceptions: Float!
  clearances: Float!
  blocks: Float!
  fouls: Float!
  ownGoals: Int!
  aerielWon: Float!
  dispossessed: Float!
}

type Fixture {
  sofascoreId: Int!
  homeId: Int!
  awayId: Int!
  machine: String
  isFriendly: Boolean
  weather: String
  stadium: String
  attendance: Int
  referee: String
  refereeStats: String
  time: DateTime!
  createdDate: DateTime
  autoTime: DateTime
  seasonStageId: Int!
  halfTime: String
  fullTime: String
  extraTime: String
  pk: String
  timeElapsed: String
  liveScore: String
  autoUrl: String
  isComplete: Boolean!
  autoComplete: Boolean!
  status: FixtureStatusEnum!
  goalUrl: String
  isScraping: Boolean!
  incidents: String
  updatedStat: Boolean
  updatedFixtureStats: Boolean
  updatedMissingPlayers: Boolean
  updatedLiveMatch: Boolean
  updatedProbableLineup: Boolean
  updatedProbableLineup404: Boolean
  updatedComment: Boolean!
  runSquawkaLive: Boolean
  runGoalLive: Boolean
  probableLineup: String
  hasVideos: Boolean!
  liveTV: String
  minuteExpanded: Int
  round: Int!
  isAwarded: Boolean!
  isTopMatch: Boolean!
  home: Stats!
  away: Stats!
  time2: String!
  isLiveMatch: Boolean!
  showStats: Boolean!
  score: String!
  fixtureCategories: [FixtureCategory!]!
  fixtureStats: [FixtureStat!]!
  fixtureComments: [FixtureComment!]!
  id: Int!
  homeTeam: Team! @cost(weight: "10")
  awayTeam: Team! @cost(weight: "10")
}

type FixtureCategory {
  categoryId: Int!
  fixtureId: Int!
  fixture: Fixture!
  id: Int!
}

type FixtureComment {
  fixtureId: Int!
  min: String!
  team: Int!
  text: String!
  action: String
  fixture: Fixture!
  id: Int!
}

type FixtureStat {
  fixtureId: Int!
  playerId: Int!
  position: String
  playablePositions: String
  xy: String
  whoscoredFormationPlace: Int
  shirtNumber: Int
  teamOwnerId: Int!
  subInMinute: Int!
  subOutMinute: Int!
  minPlayed: Int!
  shots: Int!
  shotsOnTarget: Int!
  shotsOffTarget: Int!
  shotsBlocked: Int!
  bigChanceCreated: Int!
  bigChanceMissed: Int!
  dribbles: Int!
  dribblesWon: Int!
  dribblesPast: Int!
  duelWon: Int!
  duelLost: Int!
  fouled: Int!
  fouls: Int!
  offsided: Int!
  penaltyConceded: Int!
  dispossessed: Int!
  unsTouches: Int!
  keyPasses: Int!
  accPasses: Int!
  passes: Int!
  crosses: Int!
  accCrosses: Float!
  longBall: Int!
  accLB: Float!
  throughBall: Int!
  accThB: Float!
  totalTackles: Int!
  lastManTackle: Int!
  interceptions: Int!
  possessionLost: Int!
  clearances: Int!
  blockedShots: Int!
  rating: Float!
  motm: Boolean!
  keyEvents: String
  aerialWon: Int!
  aerialLost: Int!
  groundDuelWon: Int!
  groundDuelLost: Int!
  yellowCard: Int!
  yellowRed: Int!
  redCard: Int!
  assist: Int!
  noMatches: Int!
  goal: Int!
  ownGoal: Int!
  touches: Int!
  penGoal: Int!
  penWon: Int!
  error2Goal: Int!
  clearanceOffline: Int!
  shotOnPost: Int!
  pkMissed: Int!
  pkShootoutScored: Int!
  pkShootoutMissed: Int!
  pkShootoutSaved: Int!
  throwIns: Int!
  gkSaves: Int!
  gkCatch: Int!
  gkPunch: Int!
  gkClearance: Int!
  gkTotalSweeper: Int!
  gkErrorLeadToAShot: Int!
  gkSweeper: Int!
  gkPenSaves: Int!
  isCaptain: Boolean!
  fixture: Fixture!
  id: Int!
}

type GeneralPlayerStats {
  yellow: Int!
  red: Int!
  subs: Int!
  motm: Int!
}

type GoalkeepingStats {
  saves: Float!
  cleanSheets: Float!
  goalsConceded: Float!
  penSaves: Float!
}

type LeaguePlayerAggregateDto {
  playerId: Int!
  teamOwnerId: Int!
  categoryId: Int!
  rating: Float!
  apps: Int!
  countryCSS: String
  categoryName: String
  leaguePictureId: Int
  playerName: String!
  teamPosition: String
  minPlayed: Int!
  marketValue: Float!
  customScore: Float!
  teamGoals: Int!
  general: GeneralPlayerStats!
  attacking: AttackingStats!
  passing: PassingStats!
  defending: DefendingStats!
  goalkeeping: GoalkeepingStats!
  player: Player! @cost(weight: "10")
  team: Team! @cost(weight: "10")
}

type PagedResultOfLeaguePlayerAggregateDto {
  items: [LeaguePlayerAggregateDto!]!
  pageIndex: Int!
  pageSize: Int!
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
}

type PassingStats {
  passes: Float!
  passAccuracy: Float!
  crosses: Float!
  accCrosses: Float!
  longBalls: Float!
  throughBalls: Float!
  psPercentage: Float!
  avgP: Float!
  touches: Float!
}

type Player {
  id: Int! @shareable
}

type StatInfo {
  playerId: Int!
  name: String!
  info: String!
  infoWithDecimal: String!
  info2: String!
  seName: String!
  player: Player! @cost(weight: "10")
}

type Stats {
  coach: String
  shotsGraph: String
  formation: String
  missingPlayers: String
  corner: Int!
  throwIns: Int!
  possession: Float!
  shots: Int!
  passAccuracy: Float!
  shotsOnTarget: Int!
  aerielWon: Float!
  aggressionY: Int!
  aggressionR: Int!
  rating: Float!
}

type Team {
  id: Int! @shareable
}

type TopPlayerStatsModel {
  topPerformance: [StatInfo!]!
  assist: [StatInfo!]!
  goal: [StatInfo!]!
  dribble: [StatInfo!]!
  aggression: [StatInfo!]!
  shotsPerGame: [StatInfo!]!
  passAccuracy: [StatInfo!]!
  ratings: [StatInfo!]!
  aerialsWon: [StatInfo!]!
}

type TopTeamStatDto {
  possession: [StatInfo!]!
  aggression: [StatInfo!]!
  aerialDuels: [StatInfo!]!
  shotsPerGame: [StatInfo!]!
  passAccuracy: [StatInfo!]!
  ratings: [StatInfo!]!
}

input LeaguePlayerStatsFilterInput {
  pageIndex: Int! = 0
  pageSize: Int! = 50
  countApp: Int! = 0
  teamId: Int! = 0
  fixtureId: Int! = 0
  playerName: String = ""
  teamPosition: String = ""
  categoryIds: [Int!] = []
  seasonStageIds: Int! = 0
  playerIds: [Int!] = []
  minPlayed: Int! = 0
  priceOrder: Int! = 0
  onlyRegisteredPlayers: Boolean! = true
  orderBy: LeaguePlayerOrderBy! = GOALS
  direction: SortDirection! = DESC
  timeLimit: DateTime
  timeFrom: DateTime
  timeTo: DateTime
}

"The scope of a cache hint."
enum CacheControlScope {
  "The value to cache is not tied to a single user."
  PUBLIC
  "The value to cache is specific to a single user."
  PRIVATE
}

enum FixtureStatusEnum {
  NOT_STARTED
  POSTPONED
  CANCELED
  FINISHED
  AET
}

enum LeaguePlayerOrderBy {
  RATING
  GOALS
  DEFENSE
  OFFENSE
  PASSING
  MARKET_VALUE
  APPS
  ASSISTS
  SHOTS_PER_GAME
  MINUTES
  SAVES
  AGGRESSION
  DRIBBLES
  PASS_ACCURACY
}

enum SortDirection {
  ASC
  DESC
}

"The `DateTime` scalar type represents a date and time with time zone offset information."
scalar DateTime
  @specifiedBy(url: "https://scalars.graphql.org/chillicream/date-time.html")

"The `@cacheControl` directive may be provided for individual fields or entire object, interface or union types to provide caching hints to the executor."
directive @cacheControl(
  "The maximum amount of time this field's cached value is valid, in seconds."
  maxAge: Int
  "The maximum amount of time this field's cached value is valid in shared caches like CDNs, in seconds."
  sharedMaxAge: Int
  "If `true`, the field inherits the `maxAge` of its parent field."
  inheritMaxAge: Boolean
  "If `PRIVATE`, the field's value is specific to a single user. The default value is `PUBLIC`, which means the field's value is not tied to a single user."
  scope: CacheControlScope
  "The Vary HTTP response header describes the parts of the request message aside from the method and URL that influenced the content of the response it occurs in. Most often, this is used to create a cache key when content negotiation is in use."
  vary: [String]
) on OBJECT | FIELD_DEFINITION | INTERFACE | UNION

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost(
  "The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc."
  weight: String!
) on
  | SCALAR
  | OBJECT
  | FIELD_DEFINITION
  | ARGUMENT_DEFINITION
  | ENUM
  | INPUT_FIELD_DEFINITION

directive @shareable repeatable on OBJECT | FIELD_DEFINITION
