syntax = "proto3";

option csharp_namespace = "eSport.TeamPlayer.API.Grpc";

package teamplayer;

service TeamPlayerGrpc {
  rpc GetTeams(GetTeamsRequest) returns (GetTeamsResponse);
  rpc GetSeasonStageIdsByCategory (GetSeasonStageIdsByCategoryRequest) returns (GetSeasonStageIdsByCategoryResponse);
  rpc GetRegisteredPlayerIdsBySeasonStages(GetRegisteredPlayerIdsRequest) returns (GetRegisteredPlayerIdsResponse);
  rpc GetTeamCategory(GetTeamCategoryRequest) returns (GetTeamCategoryResponse);
}
//message ~ dto class
message GetTeamsRequest {
 
  int32 categoryid = 1;
  repeated int32 season_stage_ids = 2;
}
message GetTeamsResponse {
  repeated GetTeamsMapping items = 1;
}

message GetTeamsMapping {
  int32 id = 1;
  string name = 2;
  string se_name	= 3;
}

message GetSeasonStageIdsByCategoryRequest {
  int32 category_id = 1;
}

message GetSeasonStageIdsByCategoryResponse {
  repeated int32 season_stage_ids = 1;
}

message GetRegisteredPlayerIdsRequest {
     int32 season_stage_ids = 1;
   
}
message GetRegisteredPlayerIdsResponse {
    repeated int32 registered_player_ids = 1;
}

message GetTeamCategoryRequest {
  repeated int32 team_ids = 1;
  int32 category_id = 2;
  int32 season_stage_id = 3;
}

message GetTeamCategoryResponse {
  repeated GetTeamCategoryMapping items = 1;
}
message GetTeamCategoryMapping {
  int32 team_id = 1;
  int32 category_id = 2;
  int32 season_stage_id = 3;
  int32 team_goals=4;
}