query latestSeasonsByCategory($slug: String!, $seasonStageId: Int!) {
  latestSeasonsByCategory(slug: $slug, seasonStageId: $seasonStageId) {
    currentSeasonStage {
      seasonStageId
      seasonId
      stageId
      year
      seasonDateLimit
    }

    
    seasons {
      id
      year
      displayOrder
      year2
      isActive
    }
    stages {
      id
      name
      isActive
      display
    }
    categories {
      id
      name
      seName
      

      isActive
      isTournament
      
    }
  }
}
