query latestSeasonsByCategory($slug: String!, $currentSeasonStageId: Int!) {
  latestSeasonsByCategory(slug: $slug, currentSeasonStageId: $currentSeasonStageId) {
    seasons {
      id
      year
      displayOrder
      year2
      isActive
    }
     teams {
      # id
      name
      # seName
      shortName
      # teamLogo {
      #   imageUrl
      # }
    }
    stages {
      id
      name
      isActive
      display
    }
    categories {
      id
      name
      seName
      country {
        name
        countryCSS
        threeLetterIsoCode
      }

      isActive
      isTournament
      # banner {
      #   imageUrl
      # }
    }
    currentSeasonStage {
      seasonStageId
      seasonId
      stageId
      year
      seasonDateLimit
    }
  }
}
